NEWS, import-chrome/src/import-chrome.cpp
Fixes https://github.com/wolfpld/tracy/issues/20
=> import-chrome: import zone metadata from "args" key

server/TracyView.cpp
I saw the branch on bitbucket where it didn't seem like the author was going to fix his pull request for adding horizontal scrolling, so I made this one that does the same thing but removes all the duplicated code.
=> Added support for horizontal scrolling.

.gitignore, Tracy.hpp, manual/tracy.tex
Hi! Thanks so much for this profiler, it's fantastic!
Here are a few small fixes from my end: a little .gitignore expansion so it can be used as a submodule in an automake project, some macros to handle cases that aren't currently handled.
=> Minor fixes

TracyD3D12.hpp, manual/tracy.tex
This implements the new synchronization protocol in order to mitigate GPU drift.
=> Implemented GPU synchronization for Direct3D 12

capture/build/unix/build.mk, common/unix.mk, csvexport/build/unix/build.mk, import-chrome/build/unix/build.mk, profiler/build/unix/build.mk, update/build/unix/build.mk
These are a few minor build issues I ran into trying to build on Fedora 30.
=> Build fixes for Fedora

TracyD3D12.hpp
Added TracyD3D12NewFrame stub for non-profiling configurations to compile
=> Added define for non-profiling configurations

manual/tracy.tex
=> Fix description of csvexport manual entry

TracyOpenCL.hpp
When creating an `OpenCLCtx`, the current OpenCL time calibration calls `Profiler::GetTime` for the host timestamp, then the `GetDeviceTimestamp` function to compute a device time, by recording the end time of a small memory transfer operation.  The problem is to set up that transfer, the `GetDeviceTimestamp` function makes several OpenCL calls to create a command queue, memory buffer, etc., all of which can take > 100 microseconds.  This bakes in an extra delay in host/device timestamps that effectively moves all OpenCL timestamps forward in time by that delay, leading to most OpenCL events having negative Execution Delays.
This commit is closer to the Vulkan approach: all the code in the constructor, the memory operation is queued as non-blocking, and the host timestamp is read …
=> Improve OpenCL time calibration

client/TracyProfiler.cpp
This addresses an issue (mostly present in centos7) where if the tracy client source is compiled into a shared object with a version of GCC prior to 8.4, a crash on shutdown can occur as glibc tries to destruct the `ProfilerThreadData` on the main thread after the library has unloaded.
=> Fix centos shutdown crash

TracyVulkan.hpp
to enable profiling vulkan on linux.
=> Support VK_TIME_DOMAIN_CLOCK_MONOTONIC_RAW_EXT

client/TracySysTrace.cpp
=> Fixed TracyClient.cpp compile error when using zig cc (#260).

TracyC.h, client/TracyProfiler.cpp
The new fiber APIs seem to work great! I added them to the C API and tried to follow your code style best as I could.
=> Add fibers to TracyC.h

CMakeLists.txt
=> CMakeLists: Fix typo

manual/tracy.tex
=> Mention dependency on libtbb

examples/OpenCLVectorAdd/CMakeLists.txt, examples/OpenCLVectorAdd/OpenCLVectorAdd.cpp
Add required library dependencies to CMake link target and fix trying to pass reference of lvalue
=> Fix OpenCLVectorAdd example

vcpkg/install_vcpkg_dependencies.bat
pushd %~dp0 will push the directory that contains the file as the working directory and we also pop it at the end to be a good citizen and restore the previous working directory
=> Make install_vcpkg_dendencies.bat work from any working directory

CMakeLists.txt, client/TracyProfiler.cpp, manual/tracy.tex, meson.build, meson_options.txt
We needed to add a flag to disable the crash handler as this was causing issues in our integration, maybe its useful for other folks as well?
=> Add flag to disable crash handler

server/TracySourceView.cpp
I had introduced this bug recently in https://github.com/wolfpld/tracy/pull/369
Fixes #379
=> Fix layout bug (https://github.com/wolfpld/tracy/issues/379)

client/TracyProfiler.cpp
Avoid code unreachable warning on windows #407
=> Avoid "Code is unreachable warning"

NEWS, import-chrome/src/import-chrome.cpp, server/TracyWorker.cpp
=> Import frame messages

server/TracyView_FindZone.cpp
Alternatively this should should be moved into the sections of code which call this method.
=> Add missing TreePop in function which is called from inside a TreeNode

public/client/tracy_concurrentqueue.h
Cherry-picked from
https://github.com/cameron314/concurrentqueue/commit/9dc1b2cfcad03b4ee22ea57ddb5c453c41c19ac9
=> Fix MSVC compiler warning

CMakeLists.txt, Config.cmake.in
Threads has to be added to the export target for it to work properly
=> fix missing dependendency on install

README.md
This PR adds third party binding links so the user can easily navigate them via readme.
=> Added binding links to the README.md

public/tracy/TracyD3D12.hpp
This is to untangle the tabs-to-spaces changes from https://github.com/wolfpld/tracy/pull/600
=> D3D12 back-end: converting tabs to spaces

public/tracy/TracyVulkan.hpp
Followup to [PR618](https://github.com/wolfpld/tracy/pull/618) which was closed after an unfortunate squash on my end.
To recapitulate: 
- `m_head` is now atomic, ever increasing, and only written inside NextQueryId. (`m_tail` trails `m_head` and thus is also ever increasing)
- We do not care about the sequencing of values of `m_head`, only about atomicity (and uniqueness of values returned by NextQueryId). So operations on `m_head` can use a relaxed memory order. 
- `m_tail` and `m_oldCnt` are only ever used inside Collect, thus do not require additional care
=> Fixed Vulkan query id generation not being thread safe

public/tracy/TracyVulkan.hpp
Fixes a bug introduced in #619 (by me) which causes the Vulkan implementation to run out of queries after a while.
#619 wasn't properly soak tested so it didn't show up.
=> Fixed Vulkan context running out of queries after 64k

meson.build
version had to be set to 7 minimum.
Unfortunately, I missed the release deadline.
=> fix compilation for Ubuntu MinGW

manual/tracy.tex
Hi @wolfpld ,
When looking around to find how to make system tracing work inside a docker container I found this message on the discord, that worked for me (the heart emoji is mine :smile: ). 
It was suggested to add it to the manual, I'd be glad to contribute a little to the project by doing this.
**NOTE**: I don't have latex set up on my work machine so this first version may not even compile. If you can still have a look and tell me if the change location and content seem OK, I'll then make sure to provide you with a merge-able PR
=> [doc] Add small section for docker on Ubuntu

CMakeLists.txt
=> Fix typo `enfore` -> `enforce`

import-fuchsia/src/import-fuchsia.cpp
some sample traces using that:
- https://magic-trace.org/v31.0-3d83af17c/assets/c-demo.fxt.gz
- https://magic-trace.org/v31.0-3d83af17c/assets/c-hello-world.fxt.gz
- https://magic-trace.org/v31.0-3d83af17c/assets/ocaml-hello-world.fxt.gz
=> fix import-fuchsia: handle string references properly

import-fuchsia/src/import-fuchsia.cpp
the last record might be partially written so it's important to
check bounds and dump the last record if that happens.
=> import fuchsia: check bounds to handle truncated traces

server/TracyView_FrameTree.cpp
Fix #723: Memory: active allocations are incorrectly displayed in call stack tree
The range we were looking for was wrong (should be Active instead of Inactive), but I also reworked to make the comparison clearer.
Test
Using the repro app from the bug:
1. Click "Free + Allocate" once
1. Call stack tree shows 2 entries under "Active allocations", 1 active allocation, 0 inactive allocations in the call stack tree.
1. Click "Free + Allocate" several times
1. Call stack tree shows 1 KB of active allocations and many KB of inactive.
=> Memory: correctly filter active allocations in call stack tree

CMakeLists.txt, manual/tracy.tex, python/.gitignore, python/CMakeLists.txt, python/HeaderFixer.txt, python/bindings/Memory.hpp, python/bindings/Module.cpp, python/bindings/NameBuffer.hpp, python/bindings/ScopedZone.hpp, python/setup.py, python/tracy_client/TracyClientBindings.pyi, python/tracy_client/__init__.py, python/tracy_client/scoped.py, python/tracy_client/tracy.py
Hello!
I just discovered this profiler a few days ago and I am loving it :) Thank you very much for this awesome tool! 
I noticed that there is currently no support for Python (as far as I could tell). We are using pybind11 to create python-bindings for our C++ code and were looking for a way to gain performance insights into C++ and Python at the same time. 
Tracy was the obvious choice and I added some basic Python support using pybind11.
Currently supported functionality is:
- FrameMark
- ScopedZones
- Plots
- ThreadNames
- Messages
- AppConfig
Missing support so far:
- Named FrameMarks
- Memory allocation tracking
- GPU
If you want to compile the Python-Bindings do:
```shell
mkdir build && cd build
cmake -DTRACY_STATIC=OFF -DTRACY_CLIENT_PYTHON=ON ../tracy
```
To make a Python module …
=> Added basic Python Support

profiler/src/profiler/TracyView.cpp
=> Fix Ctrl-Shift-Alt-R bug

manual/tracy.tex, profiler/src/profiler/TracyUserData.cpp, profiler/src/profiler/TracyViewData.hpp, profiler/src/profiler/TracyView_Options.cpp, profiler/src/profiler/TracyView_Plots.cpp
Plotting is useful, but once you add many, it starts taking up a lot of space rapidly. So I added a slider to shrink the plot heights.
=> Support adjusting plot height.

public/tracy/TracyD3D11.hpp
Long overdue; this addresses one of the issues reported in https://github.com/wolfpld/tracy/issues/670
=> fix TracyD3D11 "on demand"

public/client/TracyProfiler.hpp, public/client/tracy_rpmalloc.cpp
=> TracyClient Windows for ARM support

public/libbacktrace/elf.cpp
=> libbacktrace: update elf.cpp

csvexport/src/csvexport.cpp
=> add very simple plot export

csvexport/src/csvexport.cpp
This patch implements exporting user data associated with zone into CSV file.
=> Add exporting user values into CSV

update/src/OfflineSymbolResolver.cpp
See discussion https://github.com/wolfpld/tracy/issues/1075
P.S I think github editor edits the EOF for some reason...
=> relax regex match in symbolication substitution

public/tracy/TracyLua.hpp
See discussion https://github.com/wolfpld/tracy/issues/1080
=> Make TracyLua buildable with TRACY_NO_CALLSTACK
