wolfpld/tracy

- .gitignore
- capture/build/win32/capture.vcxproj
- import-chrome/build/win32/import-chrome.vcxproj
- manual/tracy.tex
- profiler/build/win32/Tracy.vcxproj
- update/build/win32/update.vcxproj
- vcpkg/install_vcpkg_dependencies.bat
This PR adds a new script `vcpkg\install_vcpkg_dependencies.bat` so that Tracy can build out of the box on Windows after you run the script.
The previous Tracy code required that you run `vcpkg integrate install` but that modifies the global Windows environment. Another way to use vcpkg is to have it build everything in a self-contained directory, rather than modify global state. This makes it possible to have different versions of vcpkg with different dependencies on the same machine. 
We're using both vcpkg and Tracy within Adobe in various ways on different projects, and we'd like to avoid `vcpkg integrate install`, so that projects are self-contained.
The .bat file does three things:
* clone vcpkg
* build vcpkg (using its bootstrap script)
* run vcpkg install ...the Tracy …
> Vcpkg dependencies

- client/TracySysTrace.cpp
- client/tracy_rpmalloc.cpp
- vcpkg/install_vcpkg_dependencies.bat
- Wrapping `FORCEINLINE `& `WIN32_LEAN_AND_MEAN` definess with ifndef bc other libraries may define it and trigger redefinition warning
- Possibly contentious given tone in the manual (:P) but removing variable shadowing in TracySysTrace.cpp
- **Alternate Solution:** Add `#define TRACY_FORCE_SILENT_WARNINGS` toggle-able flag. If flag is enabled, push/pop warning disables that have to be included in client code
- Add `-disableMetrics` to vcpkg script
P.S. I couldn't find a contributor readme/wiki page/template/style guides etc. Happy to reformulate if there is one
> Fit & Finish: Build sanitization & Static analysis warning fixes

- profiler/src/main.cpp
- server/TracyView.cpp
- set ImGuiConfigFlags_ViewportsEnable
- correct render loop logic with viewport api calls, `SetNextWindowViewport(), UpdatePlatformWindows(), RenderPlatformWindowsDefault()`
- Fix: coords in abs space now, `SetNextWindowPos()`
NOTE:
- I have viewports turned on by default so you can easy test (comment out `io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable`; and you get old behavior)
- Jankiness with multiviewports isn't bc perf hit; it's bc profiler reduces it's tick rate when it's not in focus. So, that bit of logic needs to be updated if you really care
- I haven't encountered any issues over past week but discount that by 50% since i'm new to tracy. No promises some UI wasn't regresssed
- Key things to watch out for is enabling viewports turns ImGui into using absolute monitor coords …
> ImGui Multiviewport fixes

- client/TracyCallstack.cpp
- common/TracyApi.h
- library/win32/TracyProfiler.vcxproj
- manual/tracy.tex
- server/TracyWorker.cpp
Some of stuff has accumulated in my fork. I hope it is OK to put it all into single PR, because majority of changes are so tiny. Spamming 4 PRs felt wrong somehow. If there are unacceptable changes - i will remove them and force-push.
Most important change is to how `TRACY_API` is declared. While it wasnt obviously broken - using `dllexport` for static libs was not correct. We can actually dllexport API from a static library by marking API as `dllexport` in that lib. This was not intended however. Now static builds use empty `TRACY_API` define. I also fixed header to use `TRACYPROFILER_EXPORTS` that vcxproj are already defining. And now users must define `TRACYPROFILER_IMPORTS` if they consume tracy as a dll. Manual updated for that.
I bumped into `CallTrace` in this build: …
> Misc fixes

- client/TracyLock.hpp
- client/TracyProfiler.hpp
- common/TracyQueue.hpp
GCC with -pedantic will complain about it.
> Remove extra semicolons at the end of namespaces

- server/TracySourceView.cpp
This was the only issue preventing build on macOS High Sierra with whatever version of clang it has.
> Make TracySourceView.cpp build with somewhat old clang

- client/tracy_rpmalloc.cpp
Instantiating Tracy from within a DLL will tie its internal threads life-time to the DLL. Windows does not guarantee that threads will be alive after the main function. This has implications in the Profiler dtor since will try to perform some deallocations, however, _memory_deallocate_large will try to get the heap of the current thread which can be invalid at the point of shutdown causing a crash. Checking the pointer here will won't make TRACE_NO_EXIT work, but it will prevent the Profiler from crashing.
> Fix crash when running Tracy from DLLs

- common/TracySocket.cpp
- manual/tracy.tex
Another minor change: this lets us build in a mode where the client will only listen on localhost, which operations policy can then control access to independently using typical methods like SSH or VPN tunneling.
> Add TRACY_ONLY_LOCALHOST macro to avoid listening on all interfaces.

- client/TracyProfiler.cpp
- client/TracySysTime.cpp
Just a couple warning fixes -- a use-before-init warning on regs during cpuid and an ignored-result warning on fscanf in SysTime.
> Warning fixes

- TracyVulkan.hpp
This is so that the GPU will wait for all previous commands to finish (hit bottom of pipe) before taking the enter timestamp and then whatever was recorded within the scope to finish (hit bottom of pipe) before taking the leave timestamp. TOP_OF_PIPE (particularly at the scope exit) was just recording the time of when the recorded work within the VkCtxScope was starting (hit top of the pipe) and not waiting for it to complete.
Before:
After:
> Capture Vulkan timestamps at BOTTOM_OF_PIPE instead of TOP_OF_PIPE

- Tracy.hpp
A minor change but has been something I keep locally fixing whenever I use Tracy. Figured it was time to push it back.  Great project by the way.
> Fix missing comma in ZoneScopedNCS macro

- TracyC.h
- client/TracyProfiler.cpp
- manual/tracy.tex
This function would need to be called for each non-main thread before calling
the `___tracy_alloc_`, and possibly in the future, other `___tracy` functions.
Alternative way to achieve this could be initializing the allocator
transparently in the `___tracy_alloc_*` calls.
Fixes #50
> Add ___tracy_init_thread function

- TracyC.h
- client/TracyProfiler.cpp
- client/TracyProfiler.hpp
- manual/tracy.tex
This enables better bindings in languages that do not have 0-terminated
strings for source/function name. It does not introduce any additional
overhead in languages that do use 0-terminated strings, either, but it
_is_ a breaking API change.
Fixes #53
Note: this is based on top #52 as this PR builds on top of the manual changes made there. will rebase once/if that is merged.
>  `___tracy_alloc_*` take pointer-size pairs

- .github/workflows/gcc.yml
- client/TracyProfiler.cpp
- update/src/update.cpp
It was broken by a110b420111ce02825fffaec29d08b5cc7b2168a.
In addition, adjust the CI definition to test builds on macOS.
> Fix build on macos

- TracyClient.cpp
Tracy produce some warnings when integrated, those could cause problems in pedantic builds where warnings are treated as errors.
> Disable MSVC warnings for integrated client.

- import-chrome/src/import-chrome.cpp
- server/TracyWorker.cpp
Fixes https://github.com/wolfpld/tracy/issues/54
So I can see that data is imported but is not visible in a chart. I think I need to somehow convert timestamps for plot data, because ultimately these are stored in `PlotItem.time` which is `Int48`. Are those nanoseconds from the beginning of the file? Nanoseconds since Epoch don't fit.
The metric values, at least the min and max of those are displayed correctly in the tooltip.
> Import chrome metrics

- client/TracyProfiler.cpp
On Linux `/sys` is not guaranteed to exist. When it doesn't, tracy
would crash with a SIGSEGV due to a nullptr dereference. Not actually
sure how well tracy clients will handle the case where this information
is missing, though...
> Check for null FILE handles in ReportTopology

- TracyOpenCL.hpp
To address #76
I just made sure the number of arguments in TracyOpenCL.hpp macros without TRACY_ENABLE matches the number of args with Tracy enabled.
> Fix args in OpenCL macros when !TRACY_ENABLE

- capture/build/unix/build.mk
- common/src-from-vcxproj.mk
- common/unix.mk
- csvexport/build/unix/build.mk
- import-chrome/build/unix/build.mk
- library/unix/build.mk
- profiler/build/unix/build.mk
- update/build/unix/build.mk
This pulls out most of the repeated code from the various tools' build.mk files into two shared files, `common/unix.mk` and `common/src-from-vcxproj.mk`.
> Factor out Unix build logic into shared files.

- TracyC.h
- common/TracySystem.cpp
This PR adds thread naming functionality to the Tracy C API.
> Add set thread name to C API

- server/TracyImGui.hpp
- server/TracyView.cpp
Two `bool` parameters are added to DrawStripedRect:
`fix_stripes_in_screen_space `will align the stripes of the rect in screen space. This means that any stripe rects' stripes will always exactly "line up", no matter how they are positioned to each other. When it is false, the behaviour remains unchanged.
`inverted `will flip the empty and filled aread of a striped rectangle.
When drawing the striped zones in TracyView.hpp, one zone uses inverted and one doesn't. This leads to them interleaving, which I think looks way nicer than the random partial overlaps, that happen currently.
This is what it looks like now:
I tried to match the code style, but chose more verbose names and added some comments to make it understandable. Feel free to delete the comments and pick shorter names to get it …
> Making find- and stat-zones stripes interleave always by changing DrawStripedRect

- import-chrome/src/import-chrome.cpp
The current Chrome Tracing importer incorrectly checks if the "dur" field is an object when calculating the end timestamp. The "dur" field is specified to be microseconds, not an object. This results in correctly formatted chrome traces resulting in Tracy files where each zone is zero duration.
See Chrome Tracing "spec" here: https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview#heading=h.lpfof2aylapb
> Fix timestamp calculation in chrome tracing importer

- .github/workflows/gcc.yml
- manual/tracy.tex
- profiler/build/unix/build.mk
When I tried building Tracy on another machine other than my laptop I found that GTK2.0 is needed, however, there is no mention of this dependency in the manual.
This PR adds this reference.
> Add GTK3 in the list of build requirements on Unix

- common/TracySocket.cpp
- manual/tracy.tex
When running a tracy client inside kubernetes, IPv6 port-forwarding is not available, only IPv4. It is therefore desirable to disable listening on IPv6 and use only IPv4. This patch enables such behaviour.
> Add support for TRACY_ONLY_IPV4 macro to exclude listening on IPv6

- client/tracy_concurrentqueue.h
Remove defines related to exceptions in
`tracy_concurrentqueue.h` as they are not used anywhere.
> Remove unnecessary defines in tracy_concurrentqueue.h

- manual/techdoc.tex
- profiler/build/unix/build.mk
- profiler/src/NativeWindow.cpp
- profiler/src/main.cpp
Hello, this commit lets me run Tracy on wayland.  
The display server detection is a bit basic, maybe you would prefer an environment variable switch?
GLFW gives errors about the following unsupported features:
```
Error 65548: Wayland: The platform does not support setting the input focus
Error 65548: Wayland: The platform does not support setting the window icon
Error 65548: Wayland: The platform does not support setting the window position
```
I had to add `glfwWindowHint(GLFW_ALPHA_BITS, 0);` to prevent transparent windows in Tracy from making the whole window transparent
glfw issue: https://github.com/glfw/glfw/issues/1434
I also had to remove `glfwWindowHint(GLFW_VISIBLE, 0);` to avoid this error:
```
xdg_wm_base@9: error 3: xdg_surface must not have a buffer at creation
```
which …
> Make Tracy run natively on Wayland

- profiler/build/win32/Tracy.vcxproj
Freetype references these libraries, but they are not present in the project settings.
vcpkg downloads them, but they are still not linked against.
Getting an error while trying to compile server for Tracy:
> freetype.lib(sfnt.c.obj) : error LNK2001: unresolved external symbol BrotliDecoderDecompress
> C:\dev\pbrtrr\thirdparty\tracy\profiler\build\win32\x64\Release\Tracy.exe : fatal error LNK1120: 1 unresolved externals
> added freetype references

- client/TracyProfiler.cpp
I added these inline keywords at some intermediate step where this code was in a header file, but now that it's back to this `.cpp` file they are not needed anymore.
> Fixes following PR #129

- client/TracyProfiler.cpp
Because of the layout difference between messageFat and
messageColorFat, this was referencing the text member
3-bytes offset from where it should have been.
> Fix switch for memory free.

- NEWS
- TracyD3D12.hpp
- manual/tracy.tex
This PR implements the new transient GPU zones feature for Direct3D 12, as well as removing the old callstack code to follow the new conventions.
> D3D12 transient zones

- TracyOpenCL.hpp
In `OpenCLCtxScope::SetEvent`, the necessary `clRetainEvent`
call was inside an assert, thus never called if `NDEBUG`
was defined.  This change asserts only on the return value
of the function, as in other parts of the code.
> Fix call to clRetainEvent inside assert in OpenCLCtxScope

- TracyOpenCL.hpp
Both setEvent and the destructor should
return immediately when !m_active, as the
scope is not properly initialized (m_beginQueryId
in particular.)
> Fixes for OpenCLCtxScope when not active

- .gitignore
- client/TracySysTrace.cpp
- import-chrome/src/import-chrome.cpp
- server/TracyWorker.cpp
- server/TracyWorker.hpp
Resolves #163 by adding the filename to the titlebar if the imported .tracy file does not have a name (which is the case for imported Chrome traces).
Also carries over thread names from Chrome traces.
> Improve import

- Tracy.hpp
I'm so very sorry - I had made this change locally and managed to mess up the push.  We need a triple underscore here!
> Use triple underscore in ZoneColor!

- manual/techdoc.tex
- profiler/build/unix/build.mk
- profiler/src/main.cpp
- server/TracySourceView.cpp
I tried to building without GTK, and discovered `TRACY_NO_FILESELECTOR` which helped a little, but was incomplete.  This PR adds a few more guards around usage of the file selector, and adds a build variable to control TRACY_NO_FILESELECTOR.  Additionally, linking of GTK is disabled when you pass this.  
I haven't updated the docs yet since I didn't want to do the work unless you seemed receptive to this feature.
> fix TRACY_NO_FILESELECTOR macro

- client/TracyProfiler.cpp
- common/TracySocket.cpp
- common/TracySystem.cpp
- common/TracySystem.hpp
From the code comment:
> unfortunately getenv() on Windows is just fundamentally broken.  It caches the entire environment block once on startup, then never refreshes it again.  If any environment strings are added or modified after startup of the CRT, those changes will not be seen by getenv().  This removes the possibility of an app using this SDK from programmatically setting any of the behaviour controlling envvars here.
> Windows getenv fix

- client/TracyProfiler.cpp
This codepath, involving a workaround for GCC < 8.4, called 'new' and
'delete' directly, which could cause infinite recursion when
user-provided versions of those functions were themselves using Tracy
functionality.
Now, this codepath uses Tracy's internal allocator.
See issues #194, #196
> Use tracy_malloc rather than 'new' in ProfilerThreadDataKey

- server/TracyWorker.cpp
This changes the Worker::ProcessMemFreeImpl() method so that its ev.ptr nullptr early-out happen only when there is not a previous allocation for address 0. 
Custom memory pools (like custom allocators for Vulkan memory pools) can allocate at address 0, so the previous code would generate a MemAllocTwiceFailure when this happened:
0) alloc(0, size)
1) free(0)
2) alloc(0, size2)
The issue with the old code was that in step (1) the free(0) would early-out because the ptr was null. 
The above pattern is very common in our Vulkan memory pool allocators. Those memory pools start at 0 because they are sub-allocating from a buffer, so address 0 is a valid address and shouldn't be skipped.
This change still early-outs when the ptr passed to free() is null, but only if there was not a previous …
> Change ev.ptr nullptr early-out to properly handle nullptrs

- server/TracyImGui.hpp
- server/TracyMouse.cpp
- server/TracyMouse.hpp
- server/TracySourceView.cpp
- server/TracyView.cpp
Apparently clang's `pragma once` mechanism gets confused by the fact imgui.h is included via different paths, even if they are actually the same file. While I am not sure wether this is not a bug in clang, this is how I got it back to work.
> Fix compilation on macOS 11.0.0 with XCode 12.5

- profiler/src/main.cpp
The value for paramter 'compressed_ttf_size' passed to 'AddFontFromMemoryCompressedTTF' seems to be a typo.
> The value for paramter 'compressed_ttf_size' passed to 'AddFontFromMemoryCompressedTTF' seems to be a typo.

- server/TracySourceContents.hpp
- server/tracy_robin_hood.h
When compiling with gcc 11 I get:
```
In file included from ../../../server/TracySourceContents.cpp:1:
../../../server/TracySourceContents.hpp:36:5: error: 'size_t' does not name a type
36 |     size_t m_dataSize;
|     ^~~~~~
../../../server/TracySourceContents.hpp:8:1: note: 'size_t' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
7 | #include "TracySourceTokenizer.hpp"
+++ |+#include <cstddef>
8 | 
```
and
```
In file included from ../../../server/TracySourceTokenizer.cpp:1:
../../../server/tracy_robin_hood.h: In member function 'size_t tracy::detail::Table<IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual>::calcMaxNumElementsAllowed(size_t) const':
../../../server/tracy_robin_hood.h:2122:52: error: 'numeric_limits' is not a member of 'std'
2122 |         if …
```
> build with gcc 11

- manual/tracy.tex
Without parentheses, bitwise-and takes precedence over bitwise-or.
> Tiny fix in manual

- server/TracyView.cpp
- server/TracyView.hpp
When comparing traces, where multiple classes share the same zone
names, the behavior prior to this patch was to auto-select the first
matching zone name in the other trace. Instead, find the most correct
zone by using filename and line number.
> Use file:line when comparing traces

- server/TracyWorker.cpp
Hit the problem with specific type of JSON files damage causing a crash in the `import-chrome`. While the JSON files are technically not correct, with the fix, this specific type of failure was processed alright.
The issue is that sometimes, when profiling is not properly enabled, there are asymmetric end events in the JSON profile, this is the simplest example:
[current_profile_out.json.zip](https://github.com/wolfpld/tracy/files/6680290/current_profile_out.json.zip)
This fix is generally useful since it prevents crashes. Maybe some meaningful error message should be added? In any case, with this fix, I am getting a useful file, while before the conversion utility was simply crashing with no output at all:
> Fix a crash in Worker c-tor when converting certain JSON files

- client/TracyCallstack.cpp
Sorry for the smallest PR in history, but this is what set off MS analyzer when I was updating to Tracy 0.7.8+, I thought would be good to fix it
> Fix compilation warning

- server/TracyView.cpp
> Indenting empty GPU zone tree nodes when grouped to keep zones aligned.

- client/TracyProfiler.cpp
Under unity, 
the dll(.so) will not be completely uninstalled, 
so the stack and the heap content of the thread needs to be regenerated when StartupProfiler()
> Multi Dll Proj will Crash, Under Unity

- CMakeLists.txt
- manual/tracy.tex
Add full CMake support to easily integrate it in CMake projects. (`TracyClient.cpp` had to be compiled manually before.)
Most (common) compile flags are configured as options.
I tried to implement the `libexecinfo` dependency for FreeBSD but couldn't test it.
Major parts are taken from here: https://github.com/wolfpld/tracy/issues/2#issuecomment-632594050
> Full CMake integration

- README.md
A proposal to make the documentation and binaries easier to find for newcomers.
**Background**: I struggled a bit to find the documentation first, because I was searching for a HTML documentation/link. The PDF manual is awesome, but it's well hidden in the release assets. Maybe the direct links helps some new users.
In addition, I found the compiled Win x64 binaries by lucky coincidence - they deserve to be mentioned as well in my opinion.
> Bundle links in README including latest documentation

- client/TracySysTrace.cpp
-D_WIN32_WINNT=0x601 must be defined when building TracyClient.cpp for mingw-w64 on Windows. In that case definitions I've added in my previous PR are not needed.
Sorry for the confusion.
> Undo my previous change regarding zig cc.

- TracyC.h
- client/TracyProfiler.cpp
- manual/tracy.tex
These are extremely useful for ecosystems such as Rust. There are a
couple of reasons why:
1. Rust strongly advises against relying on life before/after main, as
it is difficult to reason about. Most users working in Rust will
generally be quite surprised when encountering this concept.
2. Rust and its package manager makes it easy to use packages (crates)
and somewhat less straightforward to consider the implications of
including a dependency.
In case of the `rust_tracy_client` set of packages, I currently have
to warn throughout the documentation of the package that simply
adding a dependency on the bindings package is sufficient to
potentially accidentally broadcast a lot of information about the
instrumented binary to the broader world. This seems like a major
footgun given how easy …
> Expose TRACY_MANUAL_LIFETIME APIs to C API clients 

- server/TracyEvent.hpp
- server/TracyView.cpp
- server/TracyView.hpp
- server/TracyWorker.cpp
Give a view of the samples by "zone" to get further insight on the time spent in the instrumented zones without additional instrumentation.
(using all the samples from identical "source locations" of the whole capture)
not sure if it's done properly (I'm not very familiar with the code base, nor with the stl...)  but it seems to work for me.
~~it is limited to exclusive samples, couldn't get the inclusive to work.~~
note: It is also possible to implement along with other filtering options, but it is slow (need to examine all individual samples in the range and find the matching zone) and probably not that useful.
> Filter samples by zones source locations

- TracyOpenGL.hpp
Some OpenGL binding frameworks (glbindings (https://github.com/cginternals/glbinding) in my example) are not defining the OpenGL constants using preprocessor defines but using enum values instead.  So even when I include the file before, this check will fail as it is not a preprocessor define.  Just defining it by hand before the TracyOpenGL.h include does not work either as it leads to further compile errors down the line because of name collisions
> Removing explicit compiler define check for GL_TIMESTAMP

- TracyC.h
- client/TracyProfiler.cpp
This would close https://github.com/wolfpld/tracy/issues/180.
I wrote this via a lot of trial-and-error, so it might need a few changes before being merged. I've been using this branch of the rust bindings for testing: https://github.com/expenses/rust_tracy_client/tree/gpu-testing - [specifically via running this example](https://github.com/expenses/rust_tracy_client/blob/gpu-testing/tracy-client/examples/showcase.rs). (CC https://github.com/nagisa/rust_tracy_client/issues/19)
> Implement a bare-bones C API for graphics profiling

- CMakeLists.txt
I've been working on adding the TracyClient library to vcpkg: https://github.com/microsoft/vcpkg/pull/21826
This requires exporting the TracyClient library to make the library install-able and findable inside of vcpkg. As part of that PR it was suggested that I provide my small export patch upstream here for your consideration.
> Exporting cmake targets for install

- CMakeLists.txt
This usually prevents the compiler from emitting warnings about stuff it found in
the included files.
Since the CMakeLists.txt seems to be exclusively meant for code that is making use
of Tracy rather than Tracy itself using it to build, silencing the warnings should probably
be what most folks would want.
This will prevent things like #126
> CMake: Mark include directories as SYSTEM

- CMakeLists.txt
- TracyOpenGL.hpp
- manual/tracy.tex
When using the tracy `TRACY_ON_DEMAND` mode, it is ok in most cases to drop measurements and do a GPU clock synchronization (that may stall, sometimes up to 10ms) during the first `tracyCollect`. This is not enabled by default in the `CMakeLists.txt` for backward compatibility and because it may be a bit intrusive.
This commit also makes the OpenGL tracy `TracyGpuZone*` a tiny bit more efficient by not calling the threadlocal `GetGpuCtx()` multiple times. It is also more resilient if no context has been declared on this thread. This means that the application will not crash if a context was used on different threads even though declared only on one (thus `GetGpuCtx().ptr == nullptr`). Tracy does not support  this scenario, so on one hand this helps users by not crashing, on the other it …
> Add new TRACY_ON_DEMAND_GPU_SYNC define

- TracyD3D12.hpp
It's not enough to only call the CheckFeatureSupport, but we also have to check the actual CopyQueueTimestampQueriesSupported field of the featureData structure.
> Actually check for the required feature

- client/TracyCallstack.cpp
- client/tracy_SPSCQueue.h
The code as is produces the following warnings on MSVC with VS2019 toolchain using /W4 flags:
`
\tracy\client\tracy_SPSCQueue.h(132,1): warning C4324: 'tracy::SPSCQueue<tracy::Profiler::SymbolQueueItem>': structure was padded due to alignment specifier
\tracy\client\TracyProfiler.hpp(871): message : see reference to class template instantiation 'tracy::SPSCQueue<tracy::Profiler::SymbolQueueItem>' being compiled
\tracy\client\tracy_SPSCQueue.h(133,1): warning C4324: 'tracy::SPSCQueue<tracy::Profiler::SymbolQueueItem>': structure was padded due to alignment specifier
\tracy\client\tracy_SPSCQueue.h(134,1): warning C4324: 'tracy::SPSCQueue<tracy::Profiler::SymbolQueueItem>': structure was padded due to alignment specifier
\tracy\client\tracy_SPSCQueue.h(135,1): warning C4324: …
> Fix MSVC warnings

- client/TracyCallstack.h
- client/TracyProfiler.cpp
- client/TracySysTrace.hpp
- common/TracySystem.cpp
- common/TracyUwp.hpp
- manual/tracy.tex
We want to use Tracy in our UWP application, but some Win32 APIs are unavailable on the platform, which have to be either substituted, or the features using them have to be disabled. Traditional Win32 apps are not affected by the change.
> Make Tracy usable in UWP applications

- CMakeLists.txt
This adds the newly added `common/TracyUwp.hpp` to the list of headers to install by CMake
> Fix missing TracyUwp in the CMake headers install

- client/TracyProfiler.cpp
- client/TracyProfiler.hpp
Hi. We've recently enabled TRACY_ON_DEMAND in our development build (since we measured that there are no critical performance issues about that). 
Problem we face is that sometimes we launch our binaries in virtual machine for CI tasks. And invariant TSC is unavailable there, so application crashes.  
Most convenient solution for us - firstly try to use TSC, and if it isn't available, fallback to std::chrono.
With this PR I propose following changes in logic of TRACY_TIMER_FALLBACK macros:
If TRACY_TIMER_FALLBACK is not enabled:
* Try to use TSC 
* Fail if it isn't available
If TRACY_TIMER_FALLBACK is enabled:
* Try to use TSC 
* If can't, use std::chrono
As a result, the same binaries may be runned with or without TSC, depending on a machine.
> Automatic timer fallback

- client/TracyProfiler.cpp
- common/TracySystem.cpp
Fix two build failures when building on macOS and _GNU_SOURCE is defined.
> Fix macOS build breaks when _GNU_SOURCE defined

- server/TracyWorker.cpp
When reporting a failure and the thread context is not valid, we shouldn't access invalid memory.
I'm not sure the "default" value 0 in the error reporting function (ZoneNameFailure and ZoneTextFailure) is appropriate but it's better than an access violation.
> Avoid accessing address 0 when reporting a failure.

- server/TracyView.cpp
This fixes an assertion crash when viewing GPU zones when no zones have been
recorded on a GPU context if the client is compiled with TRACY_ON_DEMAND.
Am I understanding this correctly? Is this a reasonable fix for the issue?
> Ignore uninitialized GPU contexts when rendering GPU events

- server/TracyView.cpp
With this change full location <source>:<line> is copied to clipboard.
> In callstack table view, copy full location with line to clipboard

- manual/tracy.tex
> Warn the user about capstone deprecated branch in the manual.

- client/TracySysTrace.cpp
This wasn't technically an *uninitialized* value. Because `s_numCpus` was a global, it was implicitly zero-initialized. So we were setting `maxNumBuffers = 0` and so at [this line](https://github.com/wolfpld/tracy/blob/master/client/TracySysTrace.cpp#L828) we were calling `tracy_malloc(0)` to allocate `s_ring`.
Note, because `tracy_malloc(0)` calls `rpmalloc(0)` which currently returns a non-null pointer, we weren't necessarily crashing as soon as we dereferenced `s_ring`.  On my machine, this issue manifested itself as a crash in `rpmalloc` internals [here](https://github.com/wolfpld/tracy/blob/fd604444eb1dc5a375db28d43bb480d2641681fc/client/tracy_rpmalloc.cpp#L1285) during a subsequent allocation. It was crashing doing a `free_list_pop` on an already-empty `free_list`. I guess that the …
> set s_numCpus before reading it

- client/TracyThread.hpp
When starting/stopping tracy via manual lifetime the thread local init variable was not reset to false. Added a change to reset the variable back to false upon thread exit after the finalize function completes.
> Set thread init false on thread exit for manual lifetime cases

- capture/src/capture.cpp
According to [cppreference](https://en.cppreference.com/w/cpp/utility/program/sig_atomic_t),
> Until C++11, which introduced [std::atomic](https://en.cppreference.com/w/cpp/atomic/atomic) and [std::atomic_signal_fence](https://en.cppreference.com/w/cpp/atomic/atomic_signal_fence), about the only thing a strictly conforming program could do in a signal handler was to assign a value to a volatile static std::sig_atomic_t variable and promptly return.
The `volatile` part seems important: without it, the program may not pick up updates to this value.
The `sig_atomic_t` type per se is probably not important in practice. The spec just needed a way to limit its atomicity commitment to suitably small types. `bool` is fine from that perspective.
> Make `disconnect` atomic as it's written by a signal handler.

- capture/src/capture.cpp
This queries whether `stdout` is a terminal as opposed to another kind of file/pipe, and adjusts logging accordingly:
* Only terminals are likely to support ANSI escapes.
* Even without ANSI escapes, the data transfer progress info can make log files much larger in our experience (we run Tracy capture as part of continuous integration [here](https://buildkite.com/iree/iree-benchmark/builds)).
Notes:
* The Windows path (using `_isatty`) is untested - hope I got it right. I read Microsoft docs and saw that `<io.h>` was the right header.
* I think this actually **fixes a tiny bug** in the last ANSI escape sequence at the end of the main function in the failure case: `\033[31;1failed!` was missing the final `m` closing the escape sequence.
* Noticing: one of the places actually selects …
> make progress info and ANSI escapes conditional on being a TTY

- server/TracySourceView.cpp
Fixes:
* In the asm view, the source location column caused subsequent columns to be misaligned, and the asm jump arrows were often painted over the disassembled code.
* In both the source and asm views, the hw counters columns caused subsequent columns to be misaligned.
Note: I'm running the Tracy profiler on desktop Linux. I don't know to what extent the issues that I was seeing were specific to that.
Before: ![tracy-bad](https://user-images.githubusercontent.com/79535/164494629-a4e06645-2ac2-4df4-9ea2-4d98e3e2630b.png)
After: ![tracy-good](https://user-images.githubusercontent.com/79535/164505395-69725e7c-7cb3-4680-871e-496957dd78f9.png)
> Fix column widths for hw counts and source location

- meson.build
This PR is twofold; permission to add tracy to meson's wrapdb and a fix for the failed build on the wrapdb repo (https://github.com/mesonbuild/wrapdb/pull/399)
MSVC apparently doesn't support C++11. The relevant error from the CI:
```
Found ninja-1.10.2 at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.EXE"
WARNING: msvc does not support C++11; attempting best effort; setting the standard to C++14
ERROR: Fatal warnings enabled, aborting
```
> Removing C++11 option from msvc in meson build

- client/TracyProfiler.hpp
When we compile with warnings as errors and enable the timer fallback (for platforms that don't support the HW timer), run into an unreachable code error because the `return 0` can never be hit (i.e. either clock_gettime or std::chrono will return ahead of the return 0).
> Fix unreachable error when compiling warnings as errors + timer fallback

- import-chrome/src/import-chrome.cpp
Trivial fix: Add lower case e and b tags for chrome importer. 
When using performance.measure to capture user timings they are written by chrome with lower case "b" and "e" tags. 
This change allows importing them.
> Add lower case e and b tags

- CMakeLists.txt
I've kept the second instance of the option because the description matches what is used in `meson_options.txt`. I can update this to use whichever description you prefer.
> Remove duplicate `TRACY_NO_FRAME_IMAGE` CMake option

- CMakeLists.txt
- client/TracySysTrace.cpp
Opening this as a draft because I'm sure there are some side effects here that I'm not exactly privy to.
Tested against:
```
gcc --version
gcc (GCC) 11.2.0
```
I was curious about getting tracy working with Mingw for a side project of mine. Dug in a bit and came up with this change to just disable the body of SetupVsync when compiling with mingw. That and adding some public dependencies to make it easier to consume from CMake and this worked find with a test project of mine. However I didn't really do a complete exhaustive test. I figured discussion might be warranted / there might be a good reason why this isn't fit for upstream. I came across some gitter chat archive where mingw was known to be broken and purposefully disabled on CI but that was in the context of Mingw 8.1.0 IIRC. …
> Slight tweak to get client library working with mingw

- capture/build/unix/release.mk
- common/unix-debug.mk
- common/unix-release.mk
- csvexport/build/unix/release.mk
- import-chrome/build/unix/release.mk
- library/unix/debug.mk
- library/unix/release.mk
- profiler/build/unix/release.mk
- update/build/unix/release.mk
This adds a couple flags to the build system to allow building on systems with older compilers or targeting older CPUs. We've run into both of these in practice.
> Build adjustments

- server/TracyView.cpp
`NFD_FreePathU8` freed invalid pointer if the user closed the file selection dialog without selecting a file. Now it's the same as when opening a trace in `main.cpp`.
> Fix crash when compare trace not selected

- manual/tracy.tex
- server/TracyView.cpp
- server/TracyView.hpp
Filtering by inactive allocations helps to pin point wasteful allocations in the app.
> Add ability to filter callstacks in memory tab by inactive allocations.

- .github/workflows/msvc.yml
- capture/build/win32/capture.vcxproj
- csvexport/build/win32/csvexport.vcxproj
- import-chrome/build/win32/import-chrome.vcxproj
- profiler/build/win32/Tracy.vcxproj
- update/build/win32/update.vcxproj
- vcpkg/install_vcpkg_dependencies.bat
This PR fixes #409 by adding path to where `scripts/install_vcpkg_dependencies.bat` will install dependencies if used.
To build Tracy projects on Windows, we rely on `vcpkg` to pull third party dependencies.
There are two ways to use `vcpkg` in Tracy:
1. Either you call `scripts/install_vcpkg_dependencies.bat`, then open Visual Studio project and build them.
2. You rely on `vcpkg` msbuild integration and you can simply open Visual Studio project and build them.
The 2. requires that you have previously clone `vcpkg` somewhere on your machine and set and environment variable `VCPKG_ROOT` to that location.
Whereas 1. previously did not have this requirement but it now has.
In #365 , I broke 1. by accident as all my tests were on machine where `VCPKG_ROOT` is set (this includes Github CI).
So …
> Fix building on Windows without `VCPKG_ROOT` env var set

- libbacktrace/macho.cpp
GCC 11 and 12 installed via HomeBrew on macOS cause a compile error:
```
brew install gcc@11 gcc@12
cd tracy/test
CC=gcc-11 CXX=g++-11 make
```
```
../libbacktrace/macho.cpp: In function 'int tracy::backtrace_initialize(backtrace_state*, const char*, int, backtrace_error_callback, void*, int (**)(backtrace_state*, uintptr_t, backtrace_full_callback, backtrace_error_callback, void*))':
../libbacktrace/macho.cpp:1295:61: error: cannot convert 'tracy::macho_syminfo' from type 'void(tracy::backtrace_state*, uintptr_t, tracy::backtrace_syminfo_callback, tracy::backtrace_error_callback, void*)' {aka 'void(tracy::backtrace_state*, long unsigned int, void (*)(void*, long unsigned int, const char*, long unsigned int, long unsigned int), void (*)(void*, const char*, int), void*)'} to type 'void …
```
> Fix macOS GCC 11/12 compile error

- Tracy.hpp
This change allows the following code to compile:
if (condition)
ZoneValue(1);
else
ZoneValue(2);
All examples in the documentation already use a semicolon after a Tracy macro expression
so this shouldn't be a noticable change in behavior for most clients.
> Make Tracy.hpp compatible with if() statements without curly braces by removing trailing semicolons

- server/TracyWorker.cpp
tracy [launches multiple threads](https://github.com/wolfpld/tracy/blob/cb58b4803a2beb36d4c6cf89593865af1ef6fec3/server/TracyWorker.cpp#L1814) exec ReconstructMemAllocPlot(). In that function, [it uses lock to coordinate memory allocations between threads, but forgot to include plot->data.reserve_exact() in the locked scope too, so sometimes two data have overlap in the allocated memory block](https://github.com/wolfpld/tracy/blob/cb58b4803a2beb36d4c6cf89593865af1ef6fec3/server/TracyWorker.cpp#L7112-L7119).
> fix tracy worker threads conflict

- server/TracyEventDebug.cpp
* common/TracyQueue.hpp is now under public/.
* QueueType::PlotData is splitted by cases.
> Fix include path and QueueType::PlotData in TracyEventDebug.cpp

- CMakeLists.txt
This PR should fix issue https://github.com/wolfpld/tracy/issues/435 by updating paths that were changed to comprise the added `public/` folder.
Note that files like `Tracy.hpp` which were moved to `public/tracy/Tracy.hpp` (i.e. instead of simply `public/Tracy.hpp`) will probably require changing #include guards from `<Tracy.hpp>` into `<tracy/Tracy.hpp>`.
> Update CMakeLists.txt after directory changes

- public/tracy/TracyD3D12.hpp
As d3d12 is meant for multithreaded command list recording it is only fair to make TracyD3D12Zone threadsafe, otherwise you get weird behaviour (infinite gpu zones spanning the whole profiler window, thus not usable).
> Multithreaded d3d12 zones

- server/TracyView.hpp
- server/TracyView_Timeline.cpp
While doing this, I imlemented some clamping logic for scrolling outside the range of the timezone:
```c++
nextTimelineRangeStart = std::max<int64_t>(std::min(nextTimelineRangeStart, lastKnownTime - 50), 0);
nextTimelineRangeEnd = std::max<int64_t>(std::min(nextTimelineRangeEnd, lastKnownTime), 1);
if ( nextTimelineRangeEnd - nextTimelineRangeStart <= 50 ) return;
ZoomToRange( nextTimelineRangeStart, nextTimelineRangeEnd, !m_worker.IsConnected() || m_viewMode == ViewMode::Paused );
```
I was wondering if I should potentially add this logic to the mouse scrolling too?
Its currently a bit janky in that, if you zoom out with the mouse, beyond the bounds of the timeline - and then use the wasd keyboard navigation, it will 'snap' (still animated) into the bounds of the timeline.
Was unsure if …
> Add WASD panning/zooming functionality to timeline.

- public/client/TracyCpuid.hpp
- public/client/TracyProfiler.cpp
- public/client/TracySysTrace.cpp
Since commit 940f32c1a892dd194c3c6d66bb3550149de919fc building the Tracy
library on Linux using a GCC version < 11 would result in compile errors
due to symbol redefinitions of __get_cpuid_max, __get_cpuid and
__get_cpuid_count.
This is because prior to GCC 11 the cpuid.h header file did not have any
include guards and thus including this header more than once would
produce the abovementioned errors.
To work around this issue, including cpuid.h has been wrapped into a
custom header file that itself uses include guards and thus shields
cpuid.h from being included multiple times.
Fixes #452
> Fix cpuid symbol redefinition on older GCC versions

- CMakeLists.txt
With this new option, it is now possible to explicitly build Tracy as a
shared or static library independent from the BUILD_SHARED_LIBS
variable, which always acts on a global scope (thus, affecting all CMake
targets).
If the options is not explicitly given, it will default to whatever
BUILD_SHARED_LIBS would indicate, leaving the default behavior
unchanged.
> CMake: Add option to explicitly set lib type 

- CMakeLists.txt
In 1f7656e8454ae96f1657cf91abe8b01dc667689c I introduced a new option
but for setting its default value, I accidentally introduced invalid
cmake syntax that blows off as soon as BUILD_SHARED_LIBS is actually
defined to be non-empty.
> CMake: Fix invalid syntax

- public/client/TracyProfiler.cpp
- public/tracy/TracyC.h
I am currently integrating Tracy into a C project. Additionally to the CPU profiling I also wanted to use Tracy for GPU profiling with Vulkan. One thing that was missing compared to the C++ API was the ability to calibrate the GPU timestamps. This PR adds the ___tracy_emit_gpu_calibration and ___tracy_emit_gpu_calibration_serial calls to the C API of Tracy to be able to calibrate GPU timestamps from the C API.
> Added gpu calibration to the C API

- public/client/TracyProfiler.cpp
- public/tracy/TracyC.h
gpu_zone_begin without alloc and with callstack data were missing in the Tracy C GPU API. This should put the support of GPU tracing in the C API to the same level as the C++ API
> Added gpu zone begin non-alloc and callstack variants to the C API

- public/client/TracyProfiler.cpp
The profiled app might install handlers to track crashes, write minidumps, etc. - this patch makes sure the app's exception handler is called when a crash happens while profiling with Tracy.
> Windows exception handler allows other handlers to be called.

- server/tracy_robin_hood.h
```
error: ‘numeric_limits’ is not a member of ‘std’.
```
> Fix Fedora 36 compilation issue.

- public/client/TracyProfiler.cpp
Without this, tracy will fail to compile with the following error:
```
.../external/tracy/public/client/TracyProfiler.cpp:1524:5: error: ‘s_profilerTid’ was not declared in this scope; did you mean ‘s_profiler’?
1524 |     s_profilerTid = syscall( SYS_gettid );
|     ^~~~~~~~~~~~~
|     s_profiler
```
> Fix compile error when TRACY_NO_CRASH_HANDLER is enabled

- manual/tracy.tex
- public/client/TracyProfiler.cpp
- public/tracy/Tracy.hpp
- public/tracy/TracyC.h
- public/tracy/TracyD3D11.hpp
- public/tracy/TracyD3D12.hpp
- public/tracy/TracyOpenCL.hpp
- public/tracy/TracyOpenGL.hpp
- public/tracy/TracyVulkan.hpp
`__FUNCTION__` produces different function names under MSVC and Clang/GCC. Example:
```
struct EventSystem {
void execute() {
ZoneScoped;
// ...
}
};
struct GameplaySystem {
void execute() {
ZoneScoped;
// ...
}
};
struct RenderSystem {
void execute() {
ZoneScoped;
// ...
}
};
int main() {
EventSystem es;
GameplaySystem gs;
RenderSystem rs;
while(true) {
es.execute();
gs.execute();
rs.execute();
}
return 0;
}
```
If the binary was built under MSVC in Tracy Profiler I would see zones named: `EventSystem::execute`, `GameplaySystem::execute`, `RenderSystem::execute`.
If the binary was built under GCC or Clang in Tracy Profiler I would see zones named: `execute`, `execute`, `execute`.
The PR fixes the broblem and makes source location info more informative.
> More detailed function names under Clang and GCC

- server/TracyTimelineController.cpp
- server/TracyTimelineController.hpp
- server/TracyTimelineItem.cpp
- server/TracyTimelineItem.hpp
- server/TracyView_Timeline.cpp
* Changed the resizing logic such that when one `TimelineItem` is shrinking the `TimelineItem`s below it are following at the same speed.
* I also sneaked in a `TimelineController` height calculation fix.
* Reduced the number of lines of code.
* Tested @ 60FPS and 15FPS.
* Removed `TimelineItem::AdjustThreadPosition()` because it became obsolete.
Why:
* With this change, the `TimelineItem` shrinking is more consistent with `TimelineItem` expanding.
* Without the change each `TimelineItem` is moving at a different speed across the screen when resizing. This makes it much harder for the brain to keep track of what is happening.
* Without the change, the animations can take a very long time if a many `TimelineItem`s are resizing at the same time. To the point where in one of my use cases I …
> Timeline animation tweaks

- server/TracyUserData.cpp
- server/TracyView_ZoneInfo.cpp
- server/TracyWorker.cpp
None of the changed functions rely on the memory being zero-initialised because its initially only written to, which is why we can safely have the memory be garbage at creation. The C++ spec guarantees that `std::make_unique(std::size_t size)` with an array type always value-initialises the array/object (from cppreference):
> 2) Constructs an array of the given dynamic size. The array elements are [value-initialized](https://en.cppreference.com/w/cpp/language/value_initialization). This overload participates in overload resolution only if T is an array of unknown bound. The function is equivalent to:
`unique_ptr<T>(new std::remove_extent_t[size]())`
> Fix: Don't let make_unique initialise data unnecessarily

- public/tracy/TracyC.h
These functions are only defined when -DTRACY_FIBERS is set. However, the function is declared regardless of this def, which seems like it could lead to obscure linking errors. I haven’t encountered any of these specifically, but in my case, this difference makes it more difficult to produce correctly auto-generated bindings.
> move ___tracy_fiber* declarations to under ifdef

- capture/src/capture.cpp
The tracy worker `Exec` resets the `IsConnected` to false when finishing the capture. If it finishes too quick, the waiting loop in `capture.cpp` might not ever see `IsConnected = true`.
This changes the waiting condition to use `HasData`, which stays as true once the worker receives the data.
> Fix connection check for capturing

- public/client/TracyScoped.hpp
- public/client/TracySysTrace.cpp
Two commits which fixes compilation on linux:
1. ```public/tracy/../client/../common/TracyAlign.hpp:22:11: error: ‘type’ may be used uninitialized in this function [-Werror=maybe-uninitialized]```
2. ```public/tracy/../client/TracyScoped.hpp:102:9: error: ‘___tracy_scoped_zone.tracy::ScopedZone::m_connectionId’ may be used uninitialized in this function [-Werror=maybe-uninitialized]```
> Linux compilation fixes

- server/TracyTimelineController.cpp
- server/TracyTimelineController.hpp
- server/TracyTimelineItem.cpp
- server/TracyTimelineItem.hpp
- server/TracyTimelineItemCpuData.cpp
- server/TracyTimelineItemCpuData.hpp
- server/TracyTimelineItemGpu.cpp
- server/TracyTimelineItemPlot.cpp
- server/TracyTimelineItemThread.cpp
- server/TracyView_Timeline.cpp
This feature, when enabled in the UI (under options), changes the behavior of the timeline view when the `TimelineItem`s are resizing. The timeline view keeps the `TimelineItem` that the mouse is hovering over in its location in the view. I have made the old behavior the default because I am not confident that everybody will prefer the new behavior but I still think its ready to be included. The first two commits make sense to be merged even if the rest is not approved. I would consider #286 to be fixed with this change.
* 1st commit refactors `offset` calculation in `TimelineItem`. There should be no observable changes.
* 2nd commit fixes a off-by-one-frame error in content height calculation. The fix is needed for the feature.
* 3rd commit adds the key to the `TimelineItem`. Also needed …
> Vertical timeline centering

- public/tracy/TracyD3D11.hpp
This header used many D3D11 interfaces but didn't include the header defining them. This caused compiler errors on Windows.
> Add missing include in TracyD3D11.hpp

- public/client/TracyCallstack.cpp
There might have been new modules loaded by another thread between the `SymInitialize` and `EnumProcessModules` calls. Since we register the enumerated modules into the cache, we need to make sure that symbols for this module are loaded. The only way to do that is to call `SymLoadModuleEx`, just like we do when finding new modules after `InitCallstack`.
> Fix race condition for symbols resolution on windows

- manual/tracy.tex
- public/tracy/TracyVulkan.hpp
This adds a new constructor to the Vulkan context class that does not require to have a VkCommandBuffer and VkCommandPool created for it. It instead fully relies on host operations that were added with newer versions of Vulkan to completely avoid the use of command buffers. However, there are cases where the physical device does not support host timestamps with `vkGetCalibratedTimestampsEXT` where the command buffer based constructor would need to be used (I've placed an assertion to detect this). The user would need to check for this. (Most modern GPU drivers support this though)
I've tried to stick with the style of the rest of the header, I hope that that looks fine. However, I'm not sure wether I should be moving common code out of the constructors so that their differences are easily …
> Add: Alternative Vulkan context constructor

- public/client/TracySysTrace.cpp
This compile-time flag was being ignored on Linux.
This change adds gating for software-sampled stack trace sampling following the same pattern as the other "TRACY_NO_SAMPLE_*" options. In particular, if `TRACY_NO_SAMPLING=1` is provided as an environment variable, software stack sampling is also disabled.
> linux: respect `TRACY_NO_SAMPLING` for sys-tracing

- manual/tracy.tex
I felt like this could be a useful little hint since it can quite significantly simplify using the C api since you don't have to manually insert the zone end function everywhere a function can return.
> give a hint towards `__attribute__((cleanup)` for RAII type behavior in C

- csvexport/src/csvexport.cpp
We've noticed segfaults when exporting a tracy file to CSV in cases where one of the zones only has a single entry. The segfault is very "delicate", many things make it go away such as changing optimization level, disabling LTO, etc.
The actual segfault occurs in `std::to_string` in the line below the change in this commit but the fix here solves it, probably by avoiding the undefined behavior in this case.
The GDB backtrace to the segfaults is given below:
<details>
<summary>GDB backtrace</summary>
```
Thread 1 "tracy-csvexport" received signal SIGSEGV, Segmentation fault.
0x000000000049c2a5 in std::char_traits<char>::copy (__n=4, __s2=0x7fffffffaa70 "-nan", __s1=<optimized out>) at /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/8.1.0/bits/char_traits.h:350
350 …
```
> prevent divding by zero `csvexport` when number of zones is 1

- public/tracy/TracyVulkan.hpp
Fix towards #532, in which I forgot to add the macro in the case where `TRACY_ENABLE` is not defined. I also decided to remove the check if the `VK_EXT_calibrated_timestamps` macro is defined, because the other code paths used its functions without ever checking it either, making it totally redundant.
> Fix: Missing TracyVkContextHostCalibrated overload with Tracy disabled

- manual/tracy.tex
- public/tracy/TracyVulkan.hpp
Code assumes static linkage of the loader, while this is common, many apps opt to build their own symbol table to improve call performance (avoid the trampoline). 
Added TRACY_VK_USE_SYMBOL_TABLE to direct Tracy to load the symbols dynamically.
> Support use of dynamic vulkan symbols

- CMakeLists.txt
- version.cmake
Added a version string to the cmake to allow the shared library to be set up with correct version number and symlink. This is particularity important when incorporating Tracy into a [Yocto](https://www.yoctoproject.org/) recipe. The outcome of this change is a .so file and symlink as follows 
```
lrwxrwxrwx  1 christian christian     19 Jul 11 16:29 libTracyClient.so -> libTracyClient.so.0
lrwxrwxrwx  1 christian christian     23 Jul 11 16:29 libTracyClient.so.0 -> libTracyClient.so.0.9.1
-rwxrwxr-x  1 christian christian 829344 Jul 11 16:29 libTracyClient.so.0.9.1
```
Also replaced the hard coded share dir with the built in [cmake variable](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) for the share dir to match the rest of the cmake.
Hopefully you find these …
> Added cmake versioning and removed hardcoded share dir path

- public/client/TracyProfiler.cpp
Declaration of `s_symbolThreadGone` [wrapped with macros](https://github.com/wolfpld/tracy/blob/master/public/client/TracyProfiler.cpp#L849-L852), which is missing in the place of usage. So, compilation will fail, if you use `TRACY_NO_CALLSTACK`.
> Fix compilation for the case of using TRACY_NO_CALLSTACK

- profiler/src/main.cpp
Closes #513 
Before:
With fix applied:
> Fix macOS DPI scaling

- .github/workflows/gcc.yml
- public/client/TracyCallstack.cpp
The configuration wasn't tested and stopped compiling. This fixes it and adds a test to ensure it doesn't break again.
> Fix and test TRACY_DEMANGLE for TracyClient

- public/client/TracyProfiler.hpp
When building with TRACY_NO_FRAME_IMAGE, warning on unused parameter is triggered a lot.
> Remove warning (unused parameters)

- public/common/TracySystem.cpp
- wcstombs return (size_t)-1 to indicate error.  [reference](https://[cplusplus.com/reference/cstdlib/wcstombs/](https://cplusplus.com/reference/cstdlib/wcstombs/))
- To free the memory for the thread description, call the [LocalFree](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-localfree) method. [reference](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription)
> Fix two bugs

- public/libbacktrace/config.h
__WORDSIZE is not defined on MUSL by including limits.h only
> adapt libbacktrace to musl

- public/tracy/TracyD3D12.hpp
Here's an overview of the changes:
- removed header bloat (`<wrl/client.h>`)
- reworked context id assigning
- reworked clock calibration code
- reworked error reporting
- reworked TracyD3D12 macros
- ensure timestamps are collected when context is destroyed
> Refactoring of the D3D12 back-end

- meson.build
- meson_options.txt
It was missing from meson_options.txt breaking the build, and had an outdated name.
> Fix meson nopsleds option

- public/tracy/TracyD3D11.hpp
Summary of changes:
- better error reporting
- more frugal use of disjoint timestamp queries
- improved CPU-GPU timestamp calibration guesswork
- refactoring of redundant work in `D3D11ZoneScope` constructors
- collect pending timestamps upon context destruction
I have a planned upcoming PR to make the D3D11 back-end thread-safe in order to support deferred context command recording.
> refactoring of the D3D11 back-end

- profiler/src/BackendWayland.cpp
`zxdg_toplevel_decoration_v1` isn't a global, so the code handling it as one wasn't doing anything. Instead,
`zxdg_decoration_manager_v1_get_toplevel_decoration` returns it.
This fixes the behavior for compositors that support server-side decoration, but do not default to it until explicitly requested by the client.
> wayland: Fix use of xdg-decoration protocol

- public/tracy/TracyVulkan.hpp
`vkGetPhysicalDeviceCalibrateableTimeDomainsEXT` is an instance function, and it should be loaded via `vkGetInstanceProcAddr`.
> Correct load method for Vk instance extension symbol

- .github/workflows/gcc.yml
- meson.build
A number of meson improvements from my work to instrument Mutter and its dependencies. See individual commits.
The header install dir fix makes it work without errors, but it's still a bit ugly because it installs stuff into `/usr/include/client/` and `/usr/include/common/`. Ideally everything should go under `/usr/include/tracy/`, but that breaks some include paths relying on `../`. I might try to figure it out later.
> Meson improvements

- public/client/TracyProfiler.cpp
Same as how the C++ API does it. Otherwise with on demand mode the profiler never receives the GPU context info.
This makes things not crash, but there seems to be a different issue where GPU zones always start close to timestamp 0, rather than after the on-demand connection.
And if I connect again later, the GPU zones will still appear at the very beginning.
I'm not sure after glancing through the code what is at fault here. Moreover, even without on-demand, the GPU zones appear earlier than they should, so there might be two separate issues at play. Some of them are also overlapping weirdly. I am on AMD RX 6700M on Linux 6.5.6 and using OpenGL timestamp queries.
> Defer GPU context creation from the C API

- manual/tracy.tex
- public/client/TracyProfiler.cpp
- public/common/TracyProtocol.hpp
- public/common/TracyQueue.hpp
- public/tracy/TracyC.h
- server/TracyEventDebug.cpp
- server/TracyWorker.cpp
- server/TracyWorker.hpp
Allows to resynchronise GPU and CPU timestamps during profiling. I tested this with my Mutter setup, and it seems to work very well, even with the default power profile.
Do I need to bump the file format version and/or meson version, and to what number?
> Add GpuTimeSync event

- public/client/TracyProfiler.cpp
- public/client/TracyProfiler.hpp
- public/tracy/Tracy.hpp
- public/tracy/TracyC.h
When using TRACY_MANUAL_LIFETIME, calling most Tracy functions before starting the profiler results in an assertion. Notably, even TracyIsConnected is affected. There is, however, no function to check if the profiler had already started. This PR adds such a function.
Related: #637. This PR doesn't add any automatic checks, just allows application code to do them manually.
> Add TracyIsStarted

- manual/tracy.tex
- profiler/src/HttpRequest.cpp
- public/client/TracyProfiler.cpp
- public/common/TracySystem.cpp
This adds a basic level of support for QNX, i.e. only the instrumentation/annotation-based profiling features. Most other features haven't been tested. I've successful used this on QNX 7.0, but I think it should work for QNX 6+ at least.
> Add basic QNX support

- meson_options.txt
This allows superprojects to override the tracy_enable option. This solves a problem where toggling tracy_enable only does so in the subproject itself, adding TRACY_ENABLE definition to just the client library. Including the header in the superproject we can't use the macros as TRACY_ENABLE isn't defined.
This change allows superprojects to create a tracy_enable option that can control the subprojects option (of the same name), that way we can enable/disable profiling for everything at once, and the superproject can add the TRACY_ENABLE define itself
> Update meson_options.txt to allow overriding of tracy_enable

- CMakeLists.txt
- manual/techdoc.tex
- manual/tracy.tex
- public/client/TracyCallstack.cpp
- public/client/TracyCallstack.hpp
- public/client/TracyProfiler.cpp
Add support for using using libunwind (https://github.com/libunwind/libunwind) for performing backtraces (on linux with glibc support) - from performance tests it has shown to be significantly faster (requires client link against libunwind).
Add "TRACY_NO_DBHELP_INIT_LOAD" env var to disable driver and process module symbol loading during at init time on windows, and rely solely on demand symbol loading.
Add "TRACY_NO_SYS_TRACE" env var to allow force disabling system tracing, even if the underlying system supports it.
> Add support for using using libunwind

- profiler/build/unix/build.mk
- profiler/build/unix/legacy.mk
This PR sets the imgui include path before to pkg-config include paths to give the internal imgui include directory a higher priority. In cases imgui is installed system wide may the wrong headers are included otherwise. This may happen when using vcpkg to install dependencies and also imgui is installed with vcpkg.
> Prefer internal imgui

- meson.build
- meson_options.txt
Meson provides a build flag called `default_library` which is the standard way to specify the type of library to build. I left `tracy_shared_libs` in to prevent a breaking change.
> respect mesons default_library option

- server/TracyWorker.cpp
- server/TracyWorker.hpp
With on-demand profiling we're very likely to connect in the middle of a discontinuous frame and thus receive a frame end without any preceding frame start. So don't error out in this case.
This makes on-demand profiling usable with discontinuous frames.
If this is the right approach here, I can also remove the `FrameEnd` failure stuff altogether as it seems otherwise unused.
> Don't error on frame end without start

- CMakeLists.txt
- public/client/TracyCallstack.cpp
- public/libbacktrace/dwarf.cpp
- public/libbacktrace/elf.cpp
- public/libbacktrace/internal.hpp
On glibc platforms, add an image cache to avoid calling dladdr() when doing offline symbol resolution, as dladdr() can cause contention with other dl* calls (see: https://github.com/wolfpld/tracy/pull/665#issuecomment-1817363122).
Add support for libbacktrace to detect new elfs have been dynamically loaded after backtrace_initialize() has been called, and consider them for further symbol resolution.
> Add image cache to avoid calling dladdr() and add libbacktrace elf image list refresh

- manual/tracy.tex
- public/client/TracyProfiler.cpp
Support passing tracy client address via compile flag. Adds convenience for compiling tracy on multiple targets that have different network requirements. (In this case using QNX so can't use the default 255.255.255.255 as @michaeldleslie helped point out). 
Can add documentation in the appropriate spot.
> Add tracy client address complile flag

- public/tracy/TracyVulkan.hpp
To support loosely coupled integration of the [VulkanSceneGraph](https://github.com/vsg-dev/VulkanSceneGraph) with Tracy I had to move the VkCtx::NextQueryId() and GetId() from private to public scope, and add a VkCtx::GetQueryPool().  This change makes it possible to use the VkCtx without going via VkCtxScope and associated macros.
If these changes are deemed suitable and are merged then I can tell the VulkanSceneGraph community to just use tracy master rather than my fork's [VkCtx_public_methods](https://github.com/robertosfield/tracy/tree/VkCtx_public_methods) branch.
> Moved methods into public scope and add GetQueryPool() method to enable use of the VkCtx directly rather than just from VkCtxScope

- public/client/TracyProfiler.cpp
- public/client/TracyProfiler.hpp
This avoids the issue that an end user has their own crash handler which gets ignored when tracy is compiled in, even if tracy isn't connected to capture the crash.
> This change makes the crash handler only install when tracy is connected.

- .github/workflows/latex.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/msvc.yml
This should remove the warnings within the GitHub Actions UI about using the deprecated Node 12 and 16 versions.
> ci: Update to current versions of actions.

- public/client/TracyProfiler.cpp
Fix MSVC Warning C4244: 'argument': conversion from 'uint64_t' to 'uint32_t', possible loss of data
Since public\client\TracyProfiler.cpp is included in client code, it'd be nice to clean up this warning. It's the only warning I saw compiling v0.10 with VS2022.
We only store 32 bit thread ids in ThreadNameData. Looks like Windows threadids (`DWORD`) and Linux process ids (`pid_t`) are 32 bits so it seems fine.
Trying to follow existing style instead of static_cast.
> Fix warning: Cast thread id to uint32_t

- profiler/src/Backend.hpp
- profiler/src/BackendGlfw.cpp
- profiler/src/BackendWayland.cpp
- profiler/src/main.cpp
Right now Tracy uses the maximum scale across all advertised outputs. If you're on a mixed-DPI system, you get 2x-scaled Tracy on your 1x-scaled monitor, which looks a bit blurry.
This PR fixes and updates the scale handling:
1. Changes Tracy to use the maximum scale across all outputs that the Tracy surface is actually displaying on, rather than all advertised outputs.
- This necessitated adding a way to dynamically change the scale, since the surface can move between differently-scaled outputs.
- Behavior with `TRACY_DPI_SCALE` set was preserved.
2. With wl_compositor v6, instead of the output scale guesswork, Tracy will use the scale explicitly requested for the surface by the compositor. The compositor can generally make a better decision here, and this also makes the scale correct …
> Fix and update Wayland scale handling

- manual/techdoc.tex
- manual/tracy.tex
- [tech doc] remove section on custom thread naming 
- [user + tech doc] update macro name for `libunwind`
Sorry, my editor got rid of some trailing whitespaces on the way. I don't think that should be a problem, but I can revert that if you want.
I plan on doing some more investigation on the code and *might* find other things worthy of a MR. 
If this MR is still open I can add them there to spare you a review round - but since I don't know your release plan and there is a public doc change I wanted to provide the option to merge this right away.
> [doc] Minor documentation updates

- public/common/TracySystem.cpp
- public/common/tracy_lz4.cpp
MSVC-specific code is used in some places ([`__try`](https://github.com/wolfpld/tracy/blob/a2dd51ae4ca8fa8495faf739420d3b21f06c440b/public/common/TracySystem.cpp#L126), [`__except`](https://github.com/wolfpld/tracy/blob/a2dd51ae4ca8fa8495faf739420d3b21f06c440b/public/common/TracySystem.cpp#L130) and [`__forceinline`](https://github.com/wolfpld/tracy/blob/a2dd51ae4ca8fa8495faf739420d3b21f06c440b/public/common/tracy_lz4.cpp#L132)) and compiled only if `_MSC_VER` is set; however, Clang under Windows also defines this, which reports errors on this non-standard code if the `-pedantic-errors` compiler flag is set:
```
In file included from tracy/public/TracyClient.cpp:14:
tracy/public/common/TracySystem.cpp:126:5: error: extension used [-Werror,-Wlanguage-extension-token]
__try
^
In file …
```
> Added preprocessor checks for Clang on Windows

- manual/tracy.tex
- server/TracyView_Statistics.cpp
This copies the visible rows of either the instrumentation or GPU statistics view to a CSV string matching a subset of the csvexport format:
I noticed us sharing screenshots of the statistics view since being able the use the filter/limits of the statistics view to narrow down the zones of interest in the UI is really speedy - but screenshots aren't super usable :)
> Adding a copy to CSV button to the statistics view.

- manual/tracy.tex
- server/TracyView.cpp
This is effectively the same as clicking on the connection status button, clicking discard, and then clicking reconnect.
> Adding ctrl-r as a hotkey for reconnecting from the main profiler view.

- manual/tracy.tex
- public/client/TracyProfiler.cpp
- public/tracy/TracyC.h
This exposes the lock API to the C headers, allowing it to be used in non-C++ languages.
> Expose lock API to TracyC.h

- manual/tracy.tex
- server/TracySourceContents.cpp
- server/TracySourceContents.hpp
- server/TracySourceView.cpp
This matches the button in the call stack view:
The source content data is not guaranteed to have a NUL terminator but the ImGui clipboard API requires one so a copy is performed from the source data on-demand.
> Adding a copy button to the source view.

- public/client/TracyProfiler.cpp
- public/client/TracyProfiler.hpp
- public/client/TracyScoped.hpp
- public/tracy/TracyC.h
This pull request adds the option to specify the colour of a scoped zone for the c-api as well as for the coming Python API.
As requested, this has been split out from [Pull Request 754](https://github.com/wolfpld/tracy/pull/754).
I hope adding a default colour parameter to `tracy::Profiler::AllocSourceLocation` is okay as well as using constructor delegation for the `ScopedZone`.
> Add support to set color when creating a ScopedZone

- public/TracyClient.cpp
- public/client/TracyCallstack.hpp
- public/client/TracyProfiler.hpp
Two patches that address compilation with TRACY_NO_CALLSTACK:
- Remove build warnings about an undefined TRACY_HAS_CALLSTACK
- Still name memory pools in "MemAllocCallstackNamed()" when callstacks aren't enabled.
> Updates to address compilation with TRACY_NO_CALLSTACK

- python/bindings/Memory.hpp
- python/bindings/Module.cpp
- python/bindings/ScopedZone.hpp
Found a problem with the python-bindings when `TRACY_ENABLE=OFF`. Use the opportunity to align return values for this case as well (this allows the example script to run when tracy is disabled as well).
> Fix segfault in Python bindings for TRACE_ENABLE=OFF case

- python/CMakeLists.txt
Unfortunately cmake does not support generator expressions in add_custom_command byproducts so can't remove all files
> Do not use directories as by products when file are still present

- manual/tracy.tex
- profiler/src/profiler/TracyFilesystem.cpp
- profiler/src/profiler/TracyView.hpp
- profiler/src/profiler/TracyView_TraceInfo.cpp
Add a checkbox to allow source files to be newer then the capture
Useful on a Mac if sources are controlled via git
> Allow source file modification time to be newer then trace capture time

- public/client/TracyCallstack.cpp
Try to fix deadlocks in loader code when TRACY_USE_IMAGE_CACHE is used, see: https://github.com/wolfpld/tracy/issues/780. 
Instead of calling dladdr() inside the dl_iterate_phdr() callback, do it outside to avoid deadlocks with other loader code
> Instead of calling dladdr inside the dl_iterate_phdr callback, do it outside to avoid deadlocks with other loader code

- cmake/config.cmake
Adds /MP flag to server CMake Windows/Visual Studio configuration, to enable multi-processor compilation. This significantly speeds up clean build times, especially for the profiler.
> Server CMake: Enable multi-processor compilation in Visual Studio projects

- profiler/src/profiler/TracyView_Compare.cpp
The fraction printed represented how much of the time was left after the savings are deduced. However, as it's printed after the "Savings:" label, it makes more sense to report how much time of the original one was saved.
Going from 1s to 100ms now reports 90% savings, instead of 10%.
> Fix savings calculation.

- public/tracy/TracyVulkan.hpp
This change:
- Adds the `VK_QUERY_RESULT_WITH_AVAILABILITY_BIT` to the `vkGetQueryPoolResults` call, encoding extra data at the cost of a larger buffer (see [docs](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetQueryPoolResults.html))
- Checks that each query has been completed, and when the profiler finds a query that has not, it delays the reporting until the next time `Collect()` is called
Should solve #663
> Fix vkCmdWriteTimestamp overwrite issues

- server/TracyWorker.cpp
When TRACY_NO_STATISTICS is defined, the assert in GetGpuSourceLocationZonesCntReal will always get hit as nothing is ever inserted in gpuSourceLocationZonesCnt unless reading from a file.
Match the behavior with GetGpuSourceLocationZonesReal to add the source location if it is missing.
> Fix for assert in GetGpuSourceLocationZonesCntReal

- server/TracyWorker.cpp
Fixes incorrect length calculation for the source file string, which would lead to the source file string being completely wrong and the `StoreString` would have an overflowed size if the file name is longer than the function name.
> Fix worker AddSourceLocationPayload source file string length calculation

- test/test.cpp
Add signal handlers to trigger special conditions in `tracy-test`. This proves useful when working on the `capture` utility to check edge conditions.
example of call & output
in the profiler: 
```
❯ timeout --signal USR2 0.4 ./tracy-test
Triggering instrumentation failure
terminate called without an active exception
timeout: the monitored command dumped core
```
> [test] Trigger failures via USR1/USR2

- profiler/src/main.cpp
Both the achievement manager and the achievement data were globals in separate compilation units. Order of initialization is not defined in that case which sometimes caused the mgr to load uninitialized data and crash when an achievement should have been achieved but was not found.
> Fix achievement mgr crashing on uninitialized data

- public/client/TracyProfiler.cpp
The `__cpuidex` intrinsic is only offered by msvc. 
```
PS C:\Users\Techatrix\zls> zig c++ --version
clang version 18.1.7 (https://github.com/ziglang/zig-bootstrap ec2dca85a340f134d2fcfdc9007e91f9abed6996)
Target: x86_64-unknown-windows-gnu  
Thread model: posix
InstalledDir: C:/Users/Techatrix/zls
PS C:\Users\Techatrix\zls> zig c++ -c .\src\tracy\public\TracyClient.cpp -DTRACY_ENABLE=1
In file included from .\src\tracy\public\TracyClient.cpp:23:
.\src\tracy\public/client/TracyProfiler.cpp:312:5: error: use of undeclared identifier '__cpuidex'
312 |     __cpuidex( (int*)regs, leaf, 0 );
|     ^
1 error generated.
```
> fix CpuId when compiling with clang on windows

- CMakeLists.txt
- manual/tracy.tex
Proved very useful to debug kernel permissions issues ! I did not know it existed, so I added a small entry in the doc to mention it. It seems that's a frequent topic of discussion in the discord, that might help newcomers debug by themselves
> Expose `TRACY_VERBOSE` in cmake for debug

- CMakeLists.txt
When I link my programs to the client library, `libunwind` symbols are unresolved.
This patch addresses that issue.  I have seen that the meson script also does a similar thing.
I'm not so sure about the position of the fix inside the CMakeLists.txt, but I hope it is ok.
> Find libunwind if requested so we can link to it.

- public/client/TracySysTrace.cpp
GetSamplingInterval relies on functions that had their constexpr removed [here](https://github.com/wolfpld/tracy/commit/fb18a81d79933e50231aa345b5112a5ec0fb0613).
Should remove constexpr here as well
> Remove constexpr from GetSamplingInterval

- public/tracy/TracyLua.hpp
When a Lua script was loaded through loadstring, dbg.source is the whole source code; this not only causes a lot of unnecessary data to be sent, it can even crash Tracy if the source string is larger than 64 KB.
Therefore, use the short version which is never more than 60 characters.
> Lua: ensure source location is not longer than 255 characters

- CMakeLists.txt
- public/tracy/Tracy.hpp
> adds target export to allow use in projects using exports

- profiler/src/profiler/TracyView.cpp
- profiler/src/profiler/TracyView.hpp
- profiler/src/profiler/TracyView_Timeline.cpp
For a detailed analysis of what was the bug, see [#875](https://github.com/wolfpld/tracy/issues/875#issuecomment-2341232551). Closes #875. But in summary, the bug is due to the fact the sorting code assumes any difference in number of items in `m_threadOrder` and `worker.GetThreadData()` is exclusively due to the elements in the end of `Worker::GetThreadData()`. On the surface, this is true, but the erasing logic to process Thread Hints breaks this assumed invariant.
> Fix ThreadData-sorting bug.

- profiler/src/profiler/TracyTimelineItemThread.cpp
- profiler/src/profiler/TracyTimelineItemThread.hpp
Marked it as `const` to see better what the issue was. That's also why in my original PR, it was named "parent color": that makes clearer that it shouldn't be touched.
> Fix inheriting color bug.

- profiler/src/profiler/TracyView.hpp
- public/common/TracyProtocol.hpp
- public/common/TracyQueue.hpp
It is possible to implement custom integration in GPU zones submission
That works, but unfortunately you need to pretend to be one of existing integrations for such setup to work
This PR adds "Custom" GPU Context Type specifically for this usecase
It is by design will not be implemented in Tracy repo, and user is free to use it for custom integrations
> Added Custom GPU Context Type

- public/client/TracyProfiler.cpp
- public/client/TracyProfiler.hpp
Fix for issue #888 
Instead of attempting to read potentially unsafe memory that may be in a module that unloaded, this uses Structured Exception Handling on Windows or pipes on POSIX platforms to ensure that the entire memory region can be read.
> Safe copy to fix issue #888

- CMakeLists.txt
because the target contains architecture dependent information (for example library path) its best to store it in an architecture dependent path
other projects (for example SDL) put the their cmake files in the same place
> Export cmake config into library directory

- CMakeLists.txt
- meson.build
all headers from one project are best kept in one place
without this the headers would be spewed all over the include directory in your prefix
> Install header files into one folder

- public/client/TracySysPower.cpp
`fscanf` is `[[warn_unused_result]]`, which triggers `-Wunused-result` in GCC 13.2 + Ubuntu 24.04.
In this instance I believe it is correct for `maxRange` to remain unchanged if reading from sysfs should fail for some reason, since that error condition is checked in line 133.
> Silence GCC fscanf warning in TracySysPower.cpp

- public/client/tracy_rpmalloc.cpp
For android ndk, it is always a dynamic .so to let java load. 
So "initial-exec" would either not work, or crash for ndk 26+ with minSdk 29+.
check here: https://github.com/android/ndk/wiki/Changelog-r26#changes
[Issue 1679](https://github.com/android/ndk/issues/1679): Clang will now automatically enable ELF TLS for minSdkVersion 29 or higher.
> Fix crash on Android due to wrong TLS model

- profiler/src/profiler/TracyView.hpp
- profiler/src/profiler/TracyView_FindZone.cpp
Small contribution proposal from my side: during work on TPEG decoding messages I found it useful to have percentiles values for zone statistics. It helped me better understand the nature of the problem that I'm facing and show the gain from the improvements that I'm currently working on.
Didn't add P75 and P90 as a lines to the histogram. If you feel my contribution brings any value to core Tracy, then I can add them as well (don't use them much).
> Percentiles p75, p90 for FindZone view

- profiler/src/profiler/TracyView_ZoneInfo.cpp
For correlation with other traces (like Wireshark or tracy from another process) I find it really helpful to have an absolute timestamp in the zone info view. As all required data is available, the implementation is straightforward.
For my purposes second granularity is fine.
> Add absolute time info to Zone info view

- server/TracyWorker.cpp
For better readability display zone values not only in decimal but also in hex.
> Display zone values also in hex

- meson.build
previous check tested for compiler ID in meson, detection of an specific MSVC macro is preferred so it works in any compiler that includes the MSVC stdlib.
I noticed this error while trying to compile the `0.11.0` version
- changes the compiler check to macro check `_MSC_VER` which is an [Microsoft specific macro](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170#microsoft-specific-predefined-macros)
- changes the current defined version to `0.11.1`, previous was `0.11.0`
> [Meson][Windows] detect MSVC usage

- cmake/config.cmake
I have tried to compile Tracy with GCC on MacOS I have noticed that `-fexperimental-library` flag was set while GCC does not support this flag. This flag is also meaningless for C source code, so with this patch it will be enabled only for C++ with AppleClang compiler.
> Enable -fexperimental-library only for C++ frontend of AppleClang

- CMakeLists.txt
- public/client/TracyProfiler.cpp
Fixes #955 
I did not add a support of Meson build system
> Generate human-readable errors when TRACY_MANUAL_LIFETIME is set and TRACT_DELAYED_INIT is not

- public/client/TracyCallstack.hpp
- public/client/TracyProfiler.cpp
- public/client/TracyProfiler.hpp
- public/client/TracyScoped.hpp
- public/tracy/TracyC.h
- public/tracy/TracyD3D11.hpp
- public/tracy/TracyD3D12.hpp
- public/tracy/TracyOpenCL.hpp
- public/tracy/TracyOpenGL.hpp
- public/tracy/TracyVulkan.hpp
- python/bindings/Memory.hpp
- python/bindings/Module.cpp
- python/bindings/ScopedZone.hpp
This patch updates C API (and others too) for using `int32_t` type. After the patch,  tracy should be more portable for cases if `int` type has a size different from 4 bytes.   
Fixes #953
> Use `int32_t` type instead of `int`

- CMakeLists.txt
- manual/tracy.tex
This PR adds `TRACY_LTO` flag that enables Link-Time optimizations for Tracy. It should improve performance of Tracy calls.
> Add cross-project LTO

- csvexport/src/csvexport.cpp
**Problem solved by the commit**
tracy-csvexport cannot export gpu-zones to a csv file. 
**Solution:**
Add a new flag "-g" to this application so that tracy-csvexport can export gpu-zones to a csv file. 
eg: tracy-csvexport -g test.tracy > test.csv
When app running with this flag, instead of using GetSourceLocationZones, using GetGpuSourceLocationZones
> Export gpu zones to csv file

- python/bindings/ScopedZone.hpp
Building tracey client with Python bindings enabled is failling with the error below.
This is on a MacOS with Clang, details below.
```
In file included from /Users/phsilva/dev/tracy/python/bindings/Module.cpp:2:
/Users/phsilva/dev/tracy/python/bindings/ScopedZone.hpp:77:20: error: call to constructor of 'tracy::ScopedZone' is ambiguous
77 |       m_zone = new tracy::ScopedZone(
|                    ^
78 |           m_line, m_source.c_str(), m_source.size(), m_function.c_str(),
|           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
79 |           m_function.size(), m_name ? m_name->c_str() : nullptr,
|           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
80 |           m_name ? m_name->size() : 0ul, m_color, m_active);
| …
```
> Fix python bindings build

- profiler/src/profiler/TracyView.hpp
In Visual Studio 17.13 the STL team at Microsoft cleaned up internal includes of other public STL headers (most notably <chrono>) to increase build throughput for STL users, but now you need to include them yourself rather than rely on the indirect inclusion.
> Include <chrono> explicitly in TraceyView

- CMakeLists.txt
When you install tracy via cmake (something like cmake --build --target install) the resulting directory hierarchy differs from original inside "public" folder. Without changes in cmake file it's impossible to link against tracy built in a such way.
> Change cmake export settings to correctly copy directory hierarchy 

- meson.build
This, similar to https://github.com/wolfpld/tracy/pull/986#event-16356986891, fix the installation path of tracy when using `meson.build`.
It add also the missing `TracyKCore.hpp` header in the `client_includes`.
> Change meson install settings to correctly copy directory hierarchy

- manual/tracy.tex
- public/tracy/TracyLua.hpp
This patch implements automatic function instrumentation for Lua scripting. This mean we no longer have to manually instrument Lua code (you still have the option to if you want). Instead by using [The Debug Interface](https://www.lua.org/manual/5.4/manual.html#4.7) we can have the Lua VM invoke a callback when a function is entered or exited.
```cpp
#include <lua.hpp>
#include <tracy/Tracy.hpp>
#include <tracy/TracyLua.hpp>
lua_state* L = luaL_newstate();
// Set the hook, `LUA_MASKCALL` and `LUA_MASKRET` *MUST* be set
// If you already have a hook, you can directly invoke `tracy::LuaHook` in your own hook function.
lua_sethook(L, tracy::LuaHook, LUA_MASKCALL | LUA_MASKRET, 0);
```
With this hook function the following trace can be produced without editing *any* Lua code.
Some things to …
> Provide Lua hook function for automatic Lua instrumentation.

- profiler/CMakeLists.txt
Since since it is needed to build, we might as well enforce it through CMake to get a better error message and help finding the correct python executable since python3 may actually be only named python on windows for example.
> Let CMake discover python3 and make it required

- profiler/src/BackendWayland.cpp
Tested on niri with:
```kdl
debug {
strict-new-window-focus-policy
}
```
> wayland: Activate window with `XDG_ACTIVATION_TOKEN`.

- public/tracy/TracyD3D11.hpp
- public/tracy/TracyVulkan.hpp
With `TRACY_CALLSTACK` set to 0 when not defined, these gpu functions get called with depth=0. In other places this was alread fixed. In the debug build of tracy this would lead to the assert in `Callstack()` being triggered.
> Handle callstack of zero in Vulkan and Direct3D 11

- profiler/src/profiler/TracyView_ZoneInfo.cpp
Found this small change helpful, especially when dealing with longer user texts / cross referencing data.
> Add clipboard button for user text in ZoneInfo

- public/tracy/Tracy.hpp
Fixes #1013. Simply changed the name of the static constexpr SourceLocationData.
> Adjust LockMark() macro to allow member access expressions, like LockMark(object.mutex);

- README.md
The original link was out of date and unmaintained I've changed it to an up-to-date and maintained one
> Update link to zig bindings to an up-to-date and maintained version

- update/src/OfflineSymbolResolverAddr2Line.cpp
`addr2line` starts failing when given too many addresses to resolve. Batching per 1024 addresses allows not only to see progress but also fixes resolution for images with high number of addresses to resolve. 
Escaping is also required when image paths have spaces for example.
> tracy-update: Batch addr2line calls per 1024 addresses and escape paths

- profiler/src/BackendGlfw.cpp
This pull requests adds per monitor dpi awareness, as requested in #1034 . Specifically, if you have two monitors with different scaling set in the Windows display settings, this change will make it so the window and its contents are automatically scaled correctly according to the OS setting, when moved between monitors.
Luckily, glfw supports this directly and the changes are minimal:
- Instead of glfwGetMonitorContentScale, glfwGetWindowContentScale is used, which updates when the window is moved to a different window with different display scale setting in windows.
- By passing GLFW_SCALE_TO_MONITOR to glfwWindowHint, glfw will automatically resize the window as well. Without this the contents would be enlarged when moved to a monitor with higher scaling, but the window would stay the …
> Adding per-monitor DPI awareness

- server/TracyWorker.cpp
Instead of crashing when reaching the maximum number of source locations, display an empty source location ( with "???" everywhere). Keeping the assert for discoverability of the limit in debug, but ensure profiler won't crash later on (or in release).
> Fix crash when reaching the source location limit

- server/TracyPrint.cpp
On my system, I am getting a segmentation fault. The issue is that all these are evaluated to `false`
https://github.com/wolfpld/tracy/blob/a03c7580b9101df3225937524e09a9a885d5464a/server/TracyPrint.cpp#L262
https://github.com/wolfpld/tracy/blob/a03c7580b9101df3225937524e09a9a885d5464a/server/TracyPrint.cpp#L285
https://github.com/wolfpld/tracy/blob/a03c7580b9101df3225937524e09a9a885d5464a/server/TracyPrint.cpp#L297
https://github.com/wolfpld/tracy/blob/a03c7580b9101df3225937524e09a9a885d5464a/server/TracyPrint.cpp#L306
and then the errors occurs in
https://github.com/wolfpld/tracy/blob/a03c7580b9101df3225937524e09a9a885d5464a/server/TracyPrint.cpp#L72-L91
Here is a minimal reproducer
```c++
#include <stdio.h>
#include <stdint.h>
#include <iostream>
#include <limits>
void ko(int64_t _ns) …
```
> Time to string exact

- README.md
- manual/tracy.tex
- profiler/src/profiler/TracyView.hpp
- public/common/TracyProtocol.hpp
- public/common/TracyQueue.hpp
- public/tracy/TracyCUDA.hpp
This PR adds CUDA backend support to the Tracy profiler by integrating NVIDIA's CUPTI API. With this enhancement, Tracy can now capture and visualize GPU-related activities such as kernels, memory activities, and synchronization events.
- Integrates CUPTI (CUDA 12.8) to trace CUDA activities
- Captures kernel execution, memory operations, timing and etc
- Provides GPU context and stream association for each event
- Visualizes CUDA activities in the Tracy UI alongside CPU events
- This version is explicitly designed and tested with CUDA 12.8
- No manual instrumentation is needed because it relies on the NVIDIA CUPTI API.
> Add CUDA Backend Support to Tracy profiler

- profiler/src/BackendGlfw.cpp
- profiler/src/profiler/TracyView.cpp
trying to fix 
- https://github.com/wolfpld/tracy/issues/631
on macos 15.5 with 4k monitor and 1920x1080 resolution
before
after this pr
> fix vertical scroll bar lost  on macos

- profiler/CMakeLists.txt
Hello,
This small PR is an attempt to fix profiler compilation when the build directory is outside the source directory.
On `master`, we can easily reproduce the error with the following commands: 
```sh
cmake -S tracy/profiler -B profiler && cmake --build profiler --parallel
```
Which results in the following error:
```txt
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
make[2]: *** [CMakeFiles/git-ref.dir/build.make:70: CMakeFiles/git-ref] Error 128
make[1]: *** [CMakeFiles/Makefile2:417: CMakeFiles/git-ref.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
In this PR, I simply precise the source directory where git should be called.
Questions or changes are welcome.
And thanks a …
> Fix profiler compilation when build directory is outside the source directory

- CMakeLists.txt
When installing tracy with CMake, the new TracyMetal.hmm was not included in the list of headers to copy, this PR fixes it.
Reproduction (on posix-y shells, tested on macOS):
```
cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
cmake --build build/ --config Release --parallel
mkdir testinstall
cmake --install build --config Release --prefix "$(pwd)/testinstall" -v
```
> Add TracyMetal.hmm to the installed headers list in CMake

- manual/tracy.tex
- profiler/src/profiler/TracyView.cpp
- profiler/src/profiler/TracyView.hpp
- profiler/src/profiler/TracyView_FlameGraph.cpp
- profiler/src/profiler/TracyView_Ranges.cpp
- profiler/src/profiler/TracyView_Timeline.cpp
- profiler/src/profiler/TracyView_Utility.cpp
Allow restricting the flame graph to a specific time range.
Similar to the existing range limits for other tools, such as for statistics.
> Add limit range for flame graph.

- profiler/CMakeLists.txt
These must be added explicitly since e.g. openSUSE puts xkbcommon headers in `/usr/include/libxkbcommon/xkbcommon/xkbcommon.h` and hence fails to find the headers otherwise.
> Add include directories for pkg-config dependencies in the profiler build

- update/src/OfflineSymbolResolverAddr2Line.cpp
I think intention was to print a range?
> Fixing typo in log statement of symbolication

- public/client/TracyProfiler.cpp
This supersedes #914. I simplified it in the sense that if windows is detected without MSVC, simply disable the __try __except magic.
> Fix MinGW build.

- profiler/src/profiler/TracyView_FindZone.cpp
Previously, clicking the Clear button in the find zone search only reset the search results but did not clear the search text in the input field.
This PR updates the behavior so that the text input is also cleared when the Clear button is clicked
> Fix Clear button behavior in Find Zone

- public/client/TracyProfiler.cpp
The issue occur when the client wants to shutdown profiling but transfer all data to the server before exiting.
The client code looks like it:
`tracy::GetProfiler().RequestShutdown();`
`while (!tracy::GetProfiler().HasShutdonwFinished())`
`{`
`    yield...`
`}`
If the client doesn't send any zones/data to the queue, it works fine. But when system tracing is enabled it constantly fills queue with new data, the queue may never become empty, so we never reach exit conditions and the app hangs.
It look like solution to that problem is shutting down system tracing before sending remaining data to the server.
Another possible fix is to check `ShouldExit` in the systrace callback, but that's appear to me as a waste of cycles.
> Fix: Hang on shutdown with enabled system tracing

- profiler/src/profiler/TracyView.cpp
- profiler/src/profiler/TracyView_ConnectionState.cpp
- server/TracyWorker.cpp
- server/TracyWorker.hpp
> The links you have given do not work.
**Here are the working links, I hope this will make it clearer.**
In certain situations (notably during Tracy initialization), we observed delays caused by a form of starvation of the main thread.
The issue occurs when the worker thread quickly reacquires the mutex after releasing it — before the main thread has had a chance to wake up and acquire it itself.
This leads to a situation where the main thread is repeatedly preempted, causing noticeable lag or even temporary freezes.
Solution
To address this, we introduce a lock coordination mechanism using:
- An atomic flag: `mainThreadWantsLock`
- A condition_variable to wake the worker after the main thread is done
The `MainThreadDataLockGuard`:
- Signals that the main thread wants the lock
- Acquires …
> Add lock struct with condition variable to main thread

- profiler/src/profiler/TracyView.hpp
- profiler/src/profiler/TracyView_FindZone.cpp
Adds 99th and 99.9th percentiles to the statistics view. These metrics can be quite useful to detect stutters in e.g. a rendering engine.
> Add p99 and p99.9 stats

- .clang-format
I tried to refine a bit the `.clang-format` file that was introduced in https://github.com/wolfpld/tracy/pull/835 .
There were and still are a few issues:
> Known caveats:
- could not manage to keep small enum on a single line
This is still broken, the tool has bugs
- you put 2 spaces in ifdefs (instead of the 4 elsewhere), haven't managed to replicate it
Fixed
- it's not possible to remove the spaces around binary operators 
Still not possible.
---
I also fixed a few other things such as lambdas, spaces with templates, ...
---
I uploaded a branch with the files fully formatted with this new file here: https://github.com/wolfpld/tracy/commit/6ef555881dc2d1760448766b03f7d092cd7aff08
Things that I noticed and still aren't really good:
- short enum are still not working (even if not …
> Refine .clang-format

- profiler/src/profiler/TracyTimelineItemThread.cpp
This is kind of misleading as you may think a thread is inactive but is not. It also made it hard to inspect samples that are at the beginning of a thread where a zone might not have been called yet.
https://github.com/user-attachments/assets/a5317f1e-d2e8-4eec-8131-4a2748d7e2c6
https://github.com/user-attachments/assets/6026ce70-a260-4036-823c-797c3f23ef20
> If we have samples in view and they are displayed, timeline should be displayed even without zones

- manual/tracy.md
- manual/tracy.tex
related to the https://github.com/wolfpld/tracy/issues/1128 I've created recently:
> manual upate: OpenCL macro name fix

- public/client/TracyProfiler.hpp
I found connection check was missing for `EnterFiber` and `LeaveFiber` function. This leads to a crash when `tracy_malloc` returns NULL because m_serialQueue grows infinitely when not connected to tracy server. 
In my program, I've got thousands of fibers per second so it grows quickly.
```C++
tracy_no_inline void AllocMore()
{
const auto cap = size_t( m_end - m_ptr ) * 2;
const auto size = size_t( m_write - m_ptr );
T* ptr = (T*)tracy_malloc( sizeof( T ) * cap );
memcpy( ptr, m_ptr, size * sizeof( T ) );     // crashed here because ptr was NULL
tracy_free_fast( m_ptr );
m_ptr = ptr;
m_write = m_ptr + size;
m_end = m_ptr + cap;
}
```
> Add connection check when TRACY_ON_DEMAND for EnterFiber and LeaveFiber

- manual/tracy.tex
- profiler/src/profiler/TracyConfig.cpp
- profiler/src/profiler/TracyConfig.hpp
- profiler/src/profiler/TracyView.cpp
- profiler/src/profiler/TracyView_Options.cpp
- Button to save current options to the global Tracy Config.
- red stars indicating which options get saved.
- Added a bunch of settings I expect people to like having defaults configurable for.
- Tooltip explaining you can edit the global config file manually as well.
(fixed that awkward space after the red star in the tooltip after taking this screenshot)
Fixes #1139
> Configuration of defaults.

- manual/tracy.tex
- profiler/src/profiler/TracyView.hpp
- profiler/src/profiler/TracyView_ZoneTimeline.cpp
This PR introduces a new feature that allows users to crop the timeline on a per-thread basis, improving focus and readability when analyzing a thread with many sub-zones.
- Interactive crop toggles: Small round handles are displayed per thread on the left side of the timeline.
- Hovering over a handle displays a red guideline indicating where the crop will begin.
- Clicking a handle highlights it in white and crops the visible timeline to that thread's active zone.
- Clicking again removes the crop, restoring the full view.
This helps reduce visual clutter and makes it easier to focus on deeply nested or dense thread activity.
https://github.com/user-attachments/assets/620f3d77-3da6-461e-9246-8b0a38b76ec8
> Allow to limit zone depth

- server/TracyFileRead.hpp
Add an extra conditional alongside the other platforms that have a 64-bit `stat` for any Linux platforms that don't use glibc. Fixes #1145.
Between the widely used libc implementations for Linux, glibc is the only one that might still [use a 32-bit definition of `stat`](https://github.com/bminor/glibc/blob/d2097651cc57834dbfcaa102ddfacae0d86cfb66/bits/stat.h#L31), while [musl](https://git.musl-libc.org/cgit/musl/tree/include/sys/stat.h?h=v1.2.5#n157) and [bionic](https://android.googlesource.com/platform/bionic/+/refs/tags/android-platform-15.0.0_r11/libc/include/sys/stat.h#102) (for example), will always have a 64-bit `stat`.
Since musl doesn't even define `stat64` by default anymore, making that type aliasing ourselves becomes a necessity to avoid build errors, just as we already do for …
> Fix usage of stat64 on non-glibc Linux
